//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldClimateHydrometric
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClimateDataValue
    {
        public int ClimateDataValueID { get; set; }
        public int ClimateDataStartDateID { get; set; }
        public System.DateTime ClimateDataDateTime { get; set; }
        public Nullable<double> Temperature_C { get; set; }
        public Nullable<double> RelativeHumidity_Perc { get; set; }
        public Nullable<double> WindSpeed_kph { get; set; }
        public Nullable<double> WindDirection_0North { get; set; }
        public Nullable<double> AtmPressure_kpa { get; set; }
        public Nullable<double> Snow_cm { get; set; }
        public Nullable<double> Rainfall_mm { get; set; }
        public Nullable<double> TotalPrecip_mm_cm { get; set; }
        public Nullable<double> DewPointTemp_C { get; set; }
        public Nullable<double> MaxTemp_C { get; set; }
        public Nullable<double> MinTemp_C { get; set; }
        public Nullable<double> HeatDegDays_C { get; set; }
        public Nullable<double> CoolDegDays_C { get; set; }
        public Nullable<double> SnowOnGround_cm { get; set; }
        public Nullable<double> DirMaxGust_0North { get; set; }
        public Nullable<double> SpdMaxGust_kmh { get; set; }
    
        public virtual ClimateDataStartDate ClimateDataStartDate { get; set; }
    }
}
