//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldClimateHydrometric
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClimateStation
    {
        public ClimateStation()
        {
            this.ClimateDataStartDates = new HashSet<ClimateDataStartDate>();
        }
    
        public int ClimateStationID { get; set; }
        public int ECDBID { get; set; }
        public string ClimateStationName { get; set; }
        public string Province { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Elevation { get; set; }
        public string ClimateID { get; set; }
        public Nullable<int> WMOID { get; set; }
        public string TCID { get; set; }
        public Nullable<double> TimeOffset_hour { get; set; }
        public string File_desc { get; set; }
        public Nullable<System.DateTime> HourlyStartDate { get; set; }
        public Nullable<System.DateTime> HourlyEndDate { get; set; }
        public Nullable<bool> HourlyNow { get; set; }
        public Nullable<System.DateTime> DailyStartDate { get; set; }
        public Nullable<System.DateTime> DailyEndDate { get; set; }
        public Nullable<bool> DailyNow { get; set; }
        public Nullable<System.DateTime> MonthlyStartDate { get; set; }
        public Nullable<System.DateTime> MonthlyEndDate { get; set; }
        public Nullable<bool> MonthlyNow { get; set; }
    
        public virtual ICollection<ClimateDataStartDate> ClimateDataStartDates { get; set; }
    }
}
