//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClimateHydrometricDBEntities : DbContext
    {
        public ClimateHydrometricDBEntities()
            : base("name=ClimateHydrometricDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ClimateDataStartDate> ClimateDataStartDates { get; set; }
        public DbSet<ClimateDataValue> ClimateDataValues { get; set; }
        public DbSet<ClimateStation> ClimateStations { get; set; }
        public DbSet<HydrometricDataStartDate> HydrometricDataStartDates { get; set; }
        public DbSet<HydrometricDataValue> HydrometricDataValues { get; set; }
        public DbSet<HydrometricStation> HydrometricStations { get; set; }
        public DbSet<RatingCurve> RatingCurves { get; set; }
        public DbSet<RatingCurveValue> RatingCurveValues { get; set; }
    }
}
