//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class HydrometricStation
    {
        public HydrometricStation()
        {
            this.HydrometricDataStartDates = new HashSet<HydrometricDataStartDate>();
            this.RatingCurves = new HashSet<RatingCurve>();
        }
    
        public int HydrometricStationID { get; set; }
        public string FedStationNumber { get; set; }
        public string QuebecStationNumber { get; set; }
        public string HydrometricStationName { get; set; }
        public string Description { get; set; }
        public string Province { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Elevation { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> TimeOffset_hour { get; set; }
        public Nullable<double> DrainageArea { get; set; }
        public Nullable<bool> IsNatural { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Sediment { get; set; }
        public Nullable<bool> RHBN { get; set; }
        public Nullable<bool> RealTime { get; set; }
        public Nullable<bool> HasRatingCurve { get; set; }
    
        public virtual ICollection<HydrometricDataStartDate> HydrometricDataStartDates { get; set; }
        public virtual ICollection<RatingCurve> RatingCurves { get; set; }
    }
}
