//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class HydrometricDataStartDate
    {
        public HydrometricDataStartDate()
        {
            this.HydrometricDataValues = new HashSet<HydrometricDataValue>();
        }
    
        public int HydroMetricDataStartDateID { get; set; }
        public int HydrometricStationID { get; set; }
        public System.DateTime HydrometricDataDate { get; set; }
        public Nullable<System.DateTime> FromForcastDate { get; set; }
        public int HydrometricDataType { get; set; }
        public bool IsForcastData { get; set; }
        public bool IsObservationData { get; set; }
        public bool IsArchivedData { get; set; }
    
        public virtual HydrometricStation HydrometricStation { get; set; }
        public virtual ICollection<HydrometricDataValue> HydrometricDataValues { get; set; }
    }
}
