//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingCurveValue
    {
        public int RatingCurveValueID { get; set; }
        public int RatingCurveID { get; set; }
        public double StageValue { get; set; }
        public double DischargeValue { get; set; }
    
        public virtual RatingCurve RatingCurve { get; set; }
    }
}
