//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class box_model_dilution_s
    {
        public int MAPINFO_ID { get; set; }
        public Nullable<int> dilution_ID { get; set; }
        public Nullable<int> modele_ID { get; set; }
        public string dilution { get; set; }
        public Nullable<double> distance_calculee { get; set; }
        public Nullable<double> distance_minimale { get; set; }
        public Nullable<int> ID_Infrastructures { get; set; }
    }
}
