//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class bv_idm_final5_20mars
    {
        public int Id { get; set; }
        public Nullable<long> OBJECTID { get; set; }
        public Nullable<double> SUP_KM2 { get; set; }
        public Nullable<System.DateTime> DAT_MAJ { get; set; }
        public string ENTITE { get; set; }
        public string NOM_COURS_ { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
    }
}
