//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class BV_N1H_S_old
    {
        public Nullable<int> geodb_oid { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public double NO_SEQ_CE { get; set; }
        public string NO_CE { get; set; }
        public string NOM_BASSIN { get; set; }
        public Nullable<double> NIV_BAS { get; set; }
        public string REG_HYD { get; set; }
        public string ECHELLE { get; set; }
        public Nullable<System.DateTime> DAT_MAJ { get; set; }
        public string ENTITE { get; set; }
        public Nullable<double> SUPERF_KM2 { get; set; }
        public Nullable<double> SHAPE_Length { get; set; }
        public Nullable<double> SHAPE_Area { get; set; }
    }
}
