//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class BV_N4_S
    {
        public Nullable<decimal> NO_SEQ_CE { get; set; }
        public string NO_CE { get; set; }
        public string NOM_BASSIN { get; set; }
        public Nullable<int> NIV_BAS { get; set; }
        public string REG_HYD { get; set; }
        public string ECHELLE { get; set; }
        public Nullable<System.DateTime> DAT_MAJ { get; set; }
        public Nullable<int> SUP_KM2 { get; set; }
        public string ENTITE { get; set; }
        public Nullable<decimal> Shape_Leng { get; set; }
        public Nullable<decimal> Shape_Area { get; set; }
    }
}
