//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class BV_N1M_S_occupation_sup
    {
        public int id { get; set; }
        public Nullable<decimal> OBJECTID_1 { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public Nullable<decimal> NO_SEQ_COU { get; set; }
        public string NO_COURS_D { get; set; }
        public string NOM_COURS_ { get; set; }
        public Nullable<int> NIVEAU_BAS { get; set; }
        public Nullable<decimal> bassin_sup_m2 { get; set; }
        public Nullable<short> TYPECOUV { get; set; }
        public Nullable<decimal> occupation_sup_m2 { get; set; }
    }
}
