//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2013_Municipalité
    {
        public string CodeGeographique { get; set; }
        public string Nom { get; set; }
        public string Statut { get; set; }
        public string CodeMRC { get; set; }
        public string MRC { get; set; }
        public string CodeRegionAdministrative { get; set; }
        public string RegionAdministrative { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<double> y { get; set; }
        public Nullable<double> x { get; set; }
        public string Feuillet { get; set; }
        public string CodeNouvelleVille { get; set; }
    }
}
