//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2013_Toponymes_officiels
    {
        public int Id { get; set; }
        public string ToponymePartieSpecifique { get; set; }
        public string ToponymePartieGenerique { get; set; }
        public string TypeEntite { get; set; }
        public string CodeGeographique { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<double> y { get; set; }
        public Nullable<double> x { get; set; }
        public string FeuilletCartographique { get; set; }
        public Nullable<bool> Cartographier { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
    }
}
