//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendrier
    {
        public int calendrier_ID { get; set; }
        public Nullable<System.DateTime> calendrierdate { get; set; }
        public Nullable<int> annee { get; set; }
        public Nullable<int> mois { get; set; }
        public Nullable<int> jour { get; set; }
        public Nullable<int> joursemaine { get; set; }
        public Nullable<int> phase_lunaire { get; set; }
    }
}
