//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class caracterisation_milieu
    {
        public int secteur_id { get; set; }
        public Nullable<int> nb_bassin_versant { get; set; }
        public Nullable<double> pente_vers_secteur { get; set; }
        public Nullable<double> drainage_du_secteur { get; set; }
        public Nullable<double> pourc_occ_faible { get; set; }
        public Nullable<double> pourc_occ_modere { get; set; }
        public Nullable<double> pourc_occ_eleve { get; set; }
        public string pente_resultat { get; set; }
        public string drainage_resultat { get; set; }
        public string occupation_resultat { get; set; }
        public string resultat_final { get; set; }
    }
}
