//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCG_Nav_Aid
    {
        public int CCG_NavAidId { get; set; }
        public string BuoyId { get; set; }
        public string BuoyName { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string PositionAccuracy { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string GeneralLocation { get; set; }
        public string Region { get; set; }
        public string BuoyType { get; set; }
        public string BuoyCategory { get; set; }
        public string Buoyancy { get; set; }
        public string Function { get; set; }
        public string PeriodDuty { get; set; }
        public string LightType { get; set; }
        public string Color { get; set; }
        public string MaintBy { get; set; }
        public string Owner { get; set; }
        public string DbSource { get; set; }
        public string MainChartNo { get; set; }
        public string FileNumber { get; set; }
        public Nullable<double> LolNum { get; set; }
        public Nullable<int> EndMon { get; set; }
        public Nullable<int> LosImpo { get; set; }
        public Nullable<int> StarMon { get; set; }
    }
}
