//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHS_sounding
    {
        public int id { get; set; }
        public Nullable<int> geodb_oid { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public Nullable<int> RCID { get; set; }
        public Nullable<short> PRIM { get; set; }
        public Nullable<short> GRUP { get; set; }
        public Nullable<int> OBJL { get; set; }
        public Nullable<short> RVER { get; set; }
        public Nullable<int> AGEN { get; set; }
        public Nullable<int> FIDN { get; set; }
        public Nullable<int> FIDS { get; set; }
        public string LNAM { get; set; }
        public string LNAM_REFS__ { get; set; }
        public Nullable<short> FFPT_RIND__ { get; set; }
        public Nullable<int> EXPSOU { get; set; }
        public string NOBJNM { get; set; }
        public string OBJNAM { get; set; }
        public string QUASOU { get; set; }
        public Nullable<double> SOUACC { get; set; }
        public string TECSOU { get; set; }
        public Nullable<int> VERDAT { get; set; }
        public string STATUS { get; set; }
        public string INFORM { get; set; }
        public string NINFOM { get; set; }
        public string NTXTDS { get; set; }
        public Nullable<int> SCAMAX { get; set; }
        public Nullable<int> SCAMIN { get; set; }
        public string TXTDSC { get; set; }
        public string RECDAT { get; set; }
        public string RECIND { get; set; }
        public string SORDAT { get; set; }
        public string SORIND { get; set; }
        public Nullable<double> C_x { get; set; }
        public Nullable<double> C_y { get; set; }
        public Nullable<double> C_z { get; set; }
        public string DSNM { get; set; }
    }
}
