//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHS_PIPSOL_line
    {
        public int geodb_oid { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public Nullable<int> RCID { get; set; }
        public Nullable<short> PRIM { get; set; }
        public Nullable<short> GRUP { get; set; }
        public Nullable<int> OBJL { get; set; }
        public Nullable<short> RVER { get; set; }
        public Nullable<int> AGEN { get; set; }
        public Nullable<int> FIDN { get; set; }
        public Nullable<int> FIDS { get; set; }
        public string LNAM { get; set; }
        public string LNAM_REFS__ { get; set; }
        public Nullable<short> FFPT_RIND__ { get; set; }
        public Nullable<double> BURDEP { get; set; }
        public Nullable<int> CATPIP { get; set; }
        public Nullable<int> CONDTN { get; set; }
        public string DATEND { get; set; }
        public string DATSTA { get; set; }
        public Nullable<double> DRVAL1 { get; set; }
        public Nullable<double> DRVAL2 { get; set; }
        public string NOBJNM { get; set; }
        public string OBJNAM { get; set; }
        public Nullable<int> PRODCT { get; set; }
        public string STATUS { get; set; }
        public Nullable<double> VERACC { get; set; }
        public Nullable<double> VERLEN { get; set; }
        public Nullable<int> VERDAT { get; set; }
        public string INFORM { get; set; }
        public string NINFOM { get; set; }
        public string NTXTDS { get; set; }
        public Nullable<int> SCAMAX { get; set; }
        public Nullable<int> SCAMIN { get; set; }
        public string TXTDSC { get; set; }
        public string RECDAT { get; set; }
        public string RECIND { get; set; }
        public string SORDAT { get; set; }
        public string SORIND { get; set; }
        public Nullable<double> SHAPE_Length { get; set; }
    }
}
