//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class codification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public codification()
        {
            this.codification_description = new HashSet<codification_description>();
            this.hyperliens = new HashSet<hyperlien>();
            this.laboratoire_operateur = new HashSet<laboratoire_operateur>();
        }
    
        public int codification_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string description { get; set; }
        public Nullable<int> etat { get; set; }
        public Nullable<int> codification_old { get; set; }
        public Nullable<int> tri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<codification_description> codification_description { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hyperlien> hyperliens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<laboratoire_operateur> laboratoire_operateur { get; set; }
    }
}
