//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class cour_zone_etude
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cour_zone_etude()
        {
            this.geo_etude_courantometrie_trajectoire_l = new HashSet<geo_etude_courantometrie_trajectoire_l>();
            this.modeles = new HashSet<modele>();
        }
    
        public int id_cour_zone_etude { get; set; }
        public Nullable<int> id_reference { get; set; }
        public Nullable<int> maree { get; set; }
        public Nullable<int> region { get; set; }
        public Nullable<int> annee { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string commentaire { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<geo_etude_courantometrie_trajectoire_l> geo_etude_courantometrie_trajectoire_l { get; set; }
        public virtual Inf_TypeEntite Inf_TypeEntite { get; set; }
        public virtual Inf_TypeEntite Inf_TypeEntite1 { get; set; }
        public virtual tr_reference tr_reference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modele> modeles { get; set; }
    }
}
