//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class cour_zone_etude
    {
        public cour_zone_etude()
        {
            this.cour_trajectoire_l = new HashSet<cour_trajectoire_l>();
            this.modeles = new HashSet<modele>();
        }
    
        public int id_cour_zone_etude { get; set; }
        public Nullable<int> id_reference { get; set; }
        public Nullable<int> maree { get; set; }
        public Nullable<int> region { get; set; }
        public Nullable<int> annee { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string commentaire { get; set; }
    
        public virtual ICollection<cour_trajectoire_l> cour_trajectoire_l { get; set; }
        public virtual Inf_TypeEntite Inf_TypeEntite { get; set; }
        public virtual Inf_TypeEntite Inf_TypeEntite1 { get; set; }
        public virtual tr_reference tr_reference { get; set; }
        public virtual ICollection<modele> modeles { get; set; }
    }
}
