//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_banc_espece
    {
        public db_banc_espece()
        {
            this.db_banc_espece_exploitation = new HashSet<db_banc_espece_exploitation>();
        }
    
        public int id_db_banc_espece { get; set; }
        public Nullable<int> id_geo_banc_coquillier_s { get; set; }
        public Nullable<int> id_tr_espece { get; set; }
        public Nullable<int> densite_moyenne_tot { get; set; }
        public Nullable<int> densite_moyenne_c { get; set; }
        public Nullable<int> densite_moyenne_nc { get; set; }
        public Nullable<int> abondance { get; set; }
        public string commentaire_fr { get; set; }
        public string commentaire_en { get; set; }
        public Nullable<int> banc_source_info { get; set; }
    
        public virtual ICollection<db_banc_espece_exploitation> db_banc_espece_exploitation { get; set; }
        public virtual geo_banc_coquillier_s geo_banc_coquillier_s { get; set; }
        public virtual tr_espece tr_espece { get; set; }
    }
}
