//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_banc_secteur
    {
        public int id_db_banc_secteur { get; set; }
        public Nullable<int> id_geo_banc_coquillier_s { get; set; }
        public string secteur { get; set; }
    
        public virtual geo_banc_coquillier_s geo_banc_coquillier_s { get; set; }
    }
}
