//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_banc_source_info
    {
        public int id_db_banc_source_info { get; set; }
        public Nullable<int> id_geo_banc_coquillier_s { get; set; }
        public Nullable<int> id_contact { get; set; }
        public Nullable<int> id_reference { get; set; }
        public Nullable<System.DateTime> date_source_info { get; set; }
        public string commentaire_fr { get; set; }
        public string commentaire_en { get; set; }
    
        public virtual contact contact { get; set; }
        public virtual geo_banc_coquillier_s geo_banc_coquillier_s { get; set; }
        public virtual tr_reference tr_reference { get; set; }
    }
}
