//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_depuration
    {
        public int id_db_depuration { get; set; }
        public Nullable<int> id_geo_secteur_s { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public string description { get; set; }
    }
}
