//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_echantillonnage_planification_mensuelle
    {
        public int db_echantillonnage_planification_mensuelle1 { get; set; }
        public string secteur { get; set; }
        public Nullable<int> annee { get; set; }
        public Nullable<int> mois { get; set; }
        public Nullable<int> frequence { get; set; }
    }
}
