//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_ed_donnees_gisement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_ed_donnees_gisement()
        {
            this.db_ed_granulometrie = new HashSet<db_ed_granulometrie>();
            this.db_ed_taille = new HashSet<db_ed_taille>();
        }
    
        public int id_db_ed_donnees_gisement { get; set; }
        public int id_db_ed_echantillonnage { get; set; }
        public Nullable<int> id_geo_ed_quadrat_p { get; set; }
        public int id_tr_espece { get; set; }
        public Nullable<int> id_geo_ed_transect_l { get; set; }
        public string methode_cueillette { get; set; }
        public Nullable<int> densite_tot { get; set; }
        public Nullable<int> densite_c { get; set; }
        public Nullable<int> densite_nc { get; set; }
        public Nullable<double> biomasse_tot { get; set; }
        public Nullable<double> biomasse_c { get; set; }
        public Nullable<double> biomasse_nc { get; set; }
        public Nullable<byte> pourc_veget { get; set; }
        public string commentaire { get; set; }
        public string espece_etat { get; set; }
    
        public virtual db_ed_echantillonnage db_ed_echantillonnage { get; set; }
        public virtual geo_ed_quadrat_p geo_ed_quadrat_p { get; set; }
        public virtual geo_transect_l geo_transect_l { get; set; }
        public virtual tr_espece tr_espece { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_ed_granulometrie> db_ed_granulometrie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_ed_taille> db_ed_taille { get; set; }
    }
}
