//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_echantillonnage_planification
    {
        public int id_db_echantillonnage_planification { get; set; }
        public int id_geo_station_p { get; set; }
        public int planification { get; set; }
        public string commentaire { get; set; }
        public Nullable<int> tournee_planification_id { get; set; }
    
        public virtual geo_stations_p geo_stations_p { get; set; }
        public virtual tournee_planification tournee_planification { get; set; }
    }
}
