//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_ec_recommandation
    {
        public db_ec_recommandation()
        {
            this.db_ec_recommandation_note = new HashSet<db_ec_recommandation_note>();
        }
    
        public int id_db_ec_recommandation { get; set; }
        public Nullable<bool> validation { get; set; }
        public Nullable<int> annee_recommandation { get; set; }
        public Nullable<System.DateTime> date_recommandation { get; set; }
        public Nullable<int> id_geo_secteur_s { get; set; }
        public Nullable<int> recommandation { get; set; }
        public Nullable<bool> depuration { get; set; }
        public Nullable<bool> changement { get; set; }
        public Nullable<bool> recuperer { get; set; }
        public Nullable<bool> jamais_evalue { get; set; }
        public Nullable<bool> nouveau_secteur { get; set; }
        public string commentaire { get; set; }
    
        public virtual ICollection<db_ec_recommandation_note> db_ec_recommandation_note { get; set; }
    }
}
