//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_ec_recommandation_note
    {
        public int id_db_ec_recommandation_note { get; set; }
        public Nullable<int> id_db_ec_recommandation { get; set; }
        public string sujet { get; set; }
        public string note { get; set; }
    
        public virtual db_ec_recommandation db_ec_recommandation { get; set; }
    }
}
