//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_log_terrain
    {
        public int id_db_log_terrain { get; set; }
        public string region { get; set; }
        public Nullable<System.DateTime> activite_debut { get; set; }
        public Nullable<System.DateTime> activite_fin { get; set; }
        public Nullable<int> contact_principal { get; set; }
        public string description { get; set; }
        public string note_de_rencontre { get; set; }
    }
}
