//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_mesure
    {
        public int id_db_mesure { get; set; }
        public int id_geo_station_p { get; set; }
        public Nullable<int> id_station { get; set; }
        public int id_tournee { get; set; }
        public Nullable<short> station { get; set; }
        public Nullable<System.DateTime> hre_echantillonnage { get; set; }
        public Nullable<int> cf { get; set; }
        public Nullable<decimal> prof { get; set; }
        public Nullable<decimal> temp { get; set; }
        public Nullable<decimal> sal { get; set; }
        public Nullable<decimal> ph { get; set; }
        public Nullable<bool> valide { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
        public string commentaire { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
        public Nullable<bool> diffusable { get; set; }
    
        public virtual db_tournee db_tournee { get; set; }
        public virtual geo_stations_p geo_stations_p { get; set; }
    }
}
