//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_rapport
    {
        public int ID_rapport_content { get; set; }
        public Nullable<int> ID_rapport { get; set; }
        public Nullable<int> ID_content_type { get; set; }
        public Nullable<int> ID_Balyse { get; set; }
        public string Text_fr { get; set; }
        public string Text_en { get; set; }
        public string Description { get; set; }
    }
}
