//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_station_no_georef
    {
        public int ID_STATION { get; set; }
        public string zone_e { get; set; }
        public Nullable<int> id_geo_station_p { get; set; }
        public string STATION { get; set; }
    }
}
