//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_tournee_20171212
    {
        public int ID_Tournee { get; set; }
        public Nullable<short> tournee { get; set; }
        public int annee { get; set; }
        public int mois { get; set; }
        public int jour { get; set; }
        public Nullable<System.DateTime> hre_deb { get; set; }
        public Nullable<System.DateTime> hre_fin { get; set; }
        public Nullable<System.DateTime> hre_recep_lab { get; set; }
        public Nullable<decimal> temp_glace_recep { get; set; }
        public Nullable<decimal> temp_temoin_recep { get; set; }
        public Nullable<System.DateTime> hre_maree_h { get; set; }
        public Nullable<System.DateTime> hre_maree_b { get; set; }
        public Nullable<int> maree_principale { get; set; }
        public string pmaree_deb { get; set; }
        public string pmaree_fin { get; set; }
        public Nullable<bool> maree_ve { get; set; }
        public Nullable<bool> maree_me { get; set; }
        public Nullable<decimal> marnage { get; set; }
        public Nullable<double> precipit { get; set; }
        public Nullable<double> precipit_2jant { get; set; }
        public Nullable<double> precipit_3jant { get; set; }
        public Nullable<double> t_air_deb { get; set; }
        public Nullable<double> t_air_fin { get; set; }
        public Nullable<double> v_vent_deb { get; set; }
        public Nullable<double> v_vent_fin { get; set; }
        public Nullable<int> vent_direction_debut { get; set; }
        public Nullable<int> vent_direction_fin { get; set; }
        public Nullable<double> couvert_nuage { get; set; }
        public Nullable<double> couvert_nuage_fin { get; set; }
        public Nullable<double> mer_etat { get; set; }
        public Nullable<double> mer_etat_fin { get; set; }
        public Nullable<decimal> niveau_eau { get; set; }
        public Nullable<double> vague_hauteur { get; set; }
        public Nullable<double> vague_hauteur_fin { get; set; }
        public string consultant { get; set; }
        public string commentaire { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> date_echantillonnage { get; set; }
        public Nullable<bool> notification { get; set; }
        public Nullable<int> cf_methode_analytique { get; set; }
        public Nullable<int> laboratoire_operateur_id { get; set; }
        public Nullable<int> validation { get; set; }
        public Nullable<System.DateTime> analyse_datetime { get; set; }
        public Nullable<System.DateTime> validation_datetime { get; set; }
        public Nullable<int> approbation { get; set; }
        public Nullable<System.DateTime> approbation_date { get; set; }
    }
}
