//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_zone_secteur_station_meteo
    {
        public int db_zone_secteur_station_meteo_id { get; set; }
        public string zone_e { get; set; }
        public string secteur { get; set; }
        public Nullable<int> annee { get; set; }
        public string station_meteo_effacer_ce_champ { get; set; }
        public Nullable<int> id_station_meteo { get; set; }
    }
}
