//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_zone
    {
        public int id_zone { get; set; }
        public string zone_e { get; set; }
        public string nomzone { get; set; }
        public string region { get; set; }
        public string secteurs { get; set; }
        public string limzone1 { get; set; }
        public string classe { get; set; }
        public Nullable<System.DateTime> datclass { get; set; }
        public string exptype { get; set; }
        public string res1 { get; set; }
        public string echan1 { get; set; }
        public string pollu1 { get; set; }
        public string nomsecteurs { get; set; }
        public string s_nom { get; set; }
        public string tributaire { get; set; }
    }
}
