//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class dec
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Nomddep { get; set; }
        public string Muni { get; set; }
        public string Info { get; set; }
        public string Dateorigin { get; set; }
        public Nullable<System.DateTime> Dateoriginedate { get; set; }
        public Nullable<double> Surfacem2 { get; set; }
        public Nullable<double> Quantitetm { get; set; }
        public string Nettoyage { get; set; }
        public string Source { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
    }
}
