//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ec_Facility
    {
        public Nullable<int> ReportID { get; set; }
        public string REP_PERIOD { get; set; }
        public string NPRI_ID { get; set; }
        public string COMP_NAME { get; set; }
        public string FACI_NAME { get; set; }
        public string CITY { get; set; }
        public string PROVINCE { get; set; }
        public bool IP_NPRI { get; set; }
        public bool IP_NPRIdnmc { get; set; }
        public bool NEW_REPORTER { get; set; }
        public string CLOSURE { get; set; }
        public bool OWNERSHIP { get; set; }
        public string SOLD_DATE { get; set; }
        public string BUSINESS { get; set; }
        public string LANGUAGEEF { get; set; }
        public bool PORTABLE { get; set; }
        public bool O_ADDRESS { get; set; }
        public string TRADENAME { get; set; }
        public string TRADENAMEF { get; set; }
        public string COMP_NAMEF { get; set; }
        public string FACI_NAMEF { get; set; }
        public string URL_ADDRES { get; set; }
        public string D_B_DUNS { get; set; }
        public string CN_SI2 { get; set; }
        public string CN_SIC { get; set; }
        public string US_SIC { get; set; }
        public string NAICS2 { get; set; }
        public string NAICS4 { get; set; }
        public string NAICS6 { get; set; }
        public Nullable<double> EMPLOYEES { get; set; }
        public bool R_USED_A { get; set; }
        public bool R_USED_B { get; set; }
        public bool R_USED_C { get; set; }
        public bool R_USED_D { get; set; }
        public bool R_USED_E { get; set; }
        public bool R_USED_F { get; set; }
        public bool R_USED_G { get; set; }
        public bool R_USED_H { get; set; }
        public bool R_USED_Z { get; set; }
        public bool R_ENGA_A { get; set; }
        public bool R_ENGA_B { get; set; }
        public bool R_ENGA_C { get; set; }
        public bool R_ENGA_D { get; set; }
        public bool R_ENGA_E { get; set; }
        public bool R_ENGA_F { get; set; }
        public bool R_ENGA_G { get; set; }
        public bool R_ENGA_H { get; set; }
        public bool R_ENGA_I { get; set; }
        public bool R_ENGA_J { get; set; }
        public bool R_ENGA_K { get; set; }
        public bool R_ENGA_L { get; set; }
        public bool R_ENGA_M { get; set; }
        public bool R_ENGA_N { get; set; }
        public bool R_ENGA_O { get; set; }
        public bool R_ENGA_P { get; set; }
        public bool R_ENGA_Q { get; set; }
        public bool R_ENGA_R { get; set; }
        public bool R_ENGA_Z { get; set; }
        public bool WOOD_CREO { get; set; }
        public bool TWRs { get; set; }
        public bool PART4_SUBS { get; set; }
        public bool DAYS_SUN { get; set; }
        public bool DAYS_MON { get; set; }
        public bool DAYS_TUE { get; set; }
        public bool DAYS_WED { get; set; }
        public bool DAYS_THU { get; set; }
        public bool DAYS_FRI { get; set; }
        public bool DAYS_SAT { get; set; }
        public bool DAYS_ALL { get; set; }
        public bool HOURS_24 { get; set; }
        public bool HOURS_16 { get; set; }
        public bool HOURS_8 { get; set; }
        public bool HOURS_OTH { get; set; }
        public string HOURS_AVE { get; set; }
        public string START_TIME { get; set; }
        public bool PP_PLAN { get; set; }
        public bool PP_CEPA { get; set; }
        public bool PP_OTHE { get; set; }
        public bool PP_VOLU { get; set; }
        public bool PP_UPDA { get; set; }
        public bool PP_SUBS { get; set; }
        public bool PP_ENER { get; set; }
        public bool PP_WATE { get; set; }
        public bool PP_YesNo { get; set; }
        public bool R_PPA2_A { get; set; }
        public bool R_PPA2_B { get; set; }
        public bool R_PPA2_C { get; set; }
        public bool R_PPA2_D { get; set; }
        public bool R_PPA2_E { get; set; }
        public bool R_PPA2_F { get; set; }
        public bool R_PPA2_G { get; set; }
        public bool R_PPA2_H { get; set; }
        public bool R_PPA2_I { get; set; }
        public bool R_PPA2_A_1 { get; set; }
        public bool R_PPA2_A_2 { get; set; }
        public bool R_PPA2_A_3 { get; set; }
        public bool R_PPA2_B_1 { get; set; }
        public bool R_PPA2_B_2 { get; set; }
        public bool R_PPA2_B_3 { get; set; }
        public bool R_PPA2_B_4 { get; set; }
        public bool R_PPA2_C_1 { get; set; }
        public bool R_PPA2_C_2 { get; set; }
        public bool R_PPA2_C_3 { get; set; }
        public bool R_PPA2_C_4 { get; set; }
        public bool R_PPA2_C_5 { get; set; }
        public bool R_PPA2_C_6 { get; set; }
        public bool R_PPA2_C_7 { get; set; }
        public bool R_PPA2_C_8 { get; set; }
        public bool R_PPA2_C_9 { get; set; }
        public bool R_PPA2_C10 { get; set; }
        public bool R_PPA2_C11 { get; set; }
        public bool R_PPA2_C12 { get; set; }
        public bool R_PPA2_C13 { get; set; }
        public bool R_PPA2_C14 { get; set; }
        public bool R_PPA2_D_1 { get; set; }
        public bool R_PPA2_D_2 { get; set; }
        public bool R_PPA2_D_3 { get; set; }
        public bool R_PPA2_D_4 { get; set; }
        public bool R_PPA2_D_5 { get; set; }
        public bool R_PPA2_D_6 { get; set; }
        public bool R_PPA2_D_7 { get; set; }
        public bool R_PPA2_D_8 { get; set; }
        public bool R_PPA2_E_1 { get; set; }
        public bool R_PPA2_E_2 { get; set; }
        public bool R_PPA2_F_1 { get; set; }
        public bool R_PPA2_F_2 { get; set; }
        public bool R_PPA2_F_3 { get; set; }
        public bool R_PPA2_F_4 { get; set; }
        public bool R_PPA2_F_5 { get; set; }
        public bool R_PPA2_F_6 { get; set; }
        public bool R_PPA2_F_7 { get; set; }
        public bool R_PPA2_G_1 { get; set; }
        public bool R_PPA2_G_2 { get; set; }
        public bool R_PPA2_G_3 { get; set; }
        public bool R_PPA2_G_4 { get; set; }
        public bool R_PPA2_H_1 { get; set; }
        public string RECE_DATE { get; set; }
        public string LAST_UPD { get; set; }
        public Nullable<double> C_UPDATES { get; set; }
    }
}
