//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationRisqueSecteur
    {
        public int EvaluationRisqueSecteurID { get; set; }
        public string Secteur { get; set; }
        public Nullable<int> secteur_ID { get; set; }
        public string Risque { get; set; }
        public string PrécipitationsHistoriques20mm { get; set; }
        public string Commentaire { get; set; }
        public Nullable<int> annee { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
