//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_photographie_p
    {
        public int id_geo_photographie_p { get; set; }
        public string secteur { get; set; }
        public string region { get; set; }
        public string etat { get; set; }
        public string commentaire { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
        public Nullable<int> ig_geo_pgs_p { get; set; }
        public Nullable<int> waypoint { get; set; }
    }
}
