//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_banc_coquillier_s
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public geo_banc_coquillier_s()
        {
            this.db_banc_espece = new HashSet<db_banc_espece>();
            this.db_banc_secteur = new HashSet<db_banc_secteur>();
            this.db_banc_source_info = new HashSet<db_banc_source_info>();
            this.geo_ed_quadrat_p = new HashSet<geo_ed_quadrat_p>();
            this.geo_transect_l = new HashSet<geo_transect_l>();
        }
    
        public int id_geo_banc_coquillier_s { get; set; }
        public string risque_associe { get; set; }
        public string commentaire_fr { get; set; }
        public string auteur { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public Nullable<System.DateTime> date_mise_a_jour { get; set; }
        public Nullable<bool> etat { get; set; }
        public Nullable<bool> zone_cueillette { get; set; }
        public Nullable<decimal> x_min { get; set; }
        public Nullable<decimal> y_min { get; set; }
        public Nullable<decimal> x_max { get; set; }
        public Nullable<decimal> y_max { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_banc_espece> db_banc_espece { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_banc_secteur> db_banc_secteur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_banc_source_info> db_banc_source_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<geo_ed_quadrat_p> geo_ed_quadrat_p { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<geo_transect_l> geo_transect_l { get; set; }
    }
}
