//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_terrain_l
    {
        public int id_geo_terrain_l_s { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public string auteur { get; set; }
        public string commentaire { get; set; }
        public Nullable<bool> etat_actif { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
    }
}
