//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_etude_courantometrie_trajectoire_l
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public geo_etude_courantometrie_trajectoire_l()
        {
            this.geo_etude_courantometrie_flotteur_p = new HashSet<geo_etude_courantometrie_flotteur_p>();
        }
    
        public int id_geo_etude_courantometrie_trajectoire_l { get; set; }
        public int id_cour_zone_etude { get; set; }
        public string nom_flotteur { get; set; }
        public Nullable<double> profondeur_depart_metre { get; set; }
        public string commentaire { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
    
        public virtual cour_zone_etude cour_zone_etude { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<geo_etude_courantometrie_flotteur_p> geo_etude_courantometrie_flotteur_p { get; set; }
    }
}
