//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_secteur_s
    {
        public int id_geo_secteur_s { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public string secteur_o { get; set; }
        public Nullable<int> id_geo_secteur_s_parent { get; set; }
        public string secteur { get; set; }
        public string secteur_ltr { get; set; }
        public Nullable<int> secteur_no1 { get; set; }
        public Nullable<int> secteur_no2 { get; set; }
        public Nullable<int> secteur_no3 { get; set; }
        public Nullable<int> secteur_no4 { get; set; }
        public string aquaculture { get; set; }
        public string secteur_nom { get; set; }
        public string secteur_nom_a { get; set; }
        public string description_legale { get; set; }
        public string description_legale_a { get; set; }
        public string description_g { get; set; }
        public string description_g_a { get; set; }
        public string region { get; set; }
        public string region_a { get; set; }
        public string status { get; set; }
        public string commentaire { get; set; }
        public string commentaire_depuration { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
        public string s_nom { get; set; }
        public Nullable<bool> non_assujetti { get; set; }
        public byte[] geometry { get; set; }
        public Nullable<decimal> x_min { get; set; }
        public Nullable<decimal> y_min { get; set; }
        public Nullable<decimal> x_max { get; set; }
        public Nullable<decimal> y_max { get; set; }
        public Nullable<double> longueur_rive { get; set; }
        public Nullable<double> superficie { get; set; }
    }
}
