//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_ressource_coquillliere_s
    {
        public int id_geo_ressource_coquilliere { get; set; }
        public string priorite { get; set; }
        public string risque_associe { get; set; }
        public string forme_verif { get; set; }
        public string secteur { get; set; }
        public string type_moule { get; set; }
        public string type_moule_a { get; set; }
        public string zone_e { get; set; }
        public string region { get; set; }
        public string snrc { get; set; }
        public string numero { get; set; }
        public string abondance { get; set; }
        public string abondance_a { get; set; }
        public string utilisation { get; set; }
        public string utilisation_a { get; set; }
        public string maree { get; set; }
        public string fond { get; set; }
        public string commentaire { get; set; }
        public string auteur { get; set; }
        public Nullable<int> id_source { get; set; }
        public string source { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public Nullable<System.DateTime> date_mise_a_jour { get; set; }
        public bool etat { get; set; }
    }
}
