//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_idm_habitation_inventaire_p
    {
        public int id { get; set; }
        public Nullable<int> id_geo_pollution_p { get; set; }
        public string matricule { get; set; }
        public string adresse { get; set; }
        public string Ville { get; set; }
        public string geocodage { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<bool> non_conforme { get; set; }
        public string Conformite { get; set; }
        public string PROPRIeTAIRE { get; set; }
        public string C1er_avis { get; set; }
        public string C2e_avis { get; set; }
        public string C3e_avis { get; set; }
        public string Test_de_sol_réalisé { get; set; }
        public string Permis { get; set; }
        public string Travaux { get; set; }
        public string Note_1 { get; set; }
        public string Note_2 { get; set; }
        public string Note_3 { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
        public Nullable<int> Terrain { get; set; }
    }
}
