//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_BV_N2M_S
    {
        public int Id { get; set; }
        public Nullable<long> OBJECTID { get; set; }
        public string NO_COURS_D { get; set; }
        public string NOM_COURS_ { get; set; }
        public string NOM_COUR_1 { get; set; }
        public Nullable<long> NIVEAU_BAS { get; set; }
        public string ECHELLE { get; set; }
        public Nullable<double> SUPERF_KM2 { get; set; }
        public Nullable<double> NO_SEQ_BV_ { get; set; }
        public string NOM_BV_PRI { get; set; }
        public string NO_REG_HYD { get; set; }
        public string NOM_REG_HY { get; set; }
        public Nullable<double> NO_SEQ_COU { get; set; }
        public string IDENTIFICA { get; set; }
        public Nullable<double> Shape_Leng { get; set; }
        public Nullable<double> Shape_Area { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
    }
}
