//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEO_BANC_COQUILLIER_S_ZVALID999
    {
        public Nullable<decimal> Id { get; set; }
        public int MI_PRINX { get; set; }
        public System.Data.Entity.Spatial.DbGeography SP_GEOMETRY { get; set; }
    }
}
