//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_chs_pipesol
    {
        public int Id { get; set; }
        public Nullable<long> RCID { get; set; }
        public Nullable<int> PRIM { get; set; }
        public Nullable<int> GRUP { get; set; }
        public Nullable<long> OBJL { get; set; }
        public Nullable<int> RVER { get; set; }
        public Nullable<long> AGEN { get; set; }
        public Nullable<long> FIDN { get; set; }
        public Nullable<long> FIDS { get; set; }
        public string LNAM { get; set; }
        public string LNAM_REFS_ { get; set; }
        public Nullable<int> FFPT_RIND_ { get; set; }
        public Nullable<float> BURDEP { get; set; }
        public string CATPIP { get; set; }
        public Nullable<long> CONDTN { get; set; }
        public string DATEND { get; set; }
        public string DATSTA { get; set; }
        public Nullable<float> DRVAL1 { get; set; }
        public Nullable<float> DRVAL2 { get; set; }
        public string NOBJNM { get; set; }
        public string OBJNAM { get; set; }
        public string PRODCT { get; set; }
        public string STATUS { get; set; }
        public Nullable<float> VERACC { get; set; }
        public Nullable<float> VERLEN { get; set; }
        public Nullable<long> VERDAT { get; set; }
        public string INFORM { get; set; }
        public string NINFOM { get; set; }
        public string NTXTDS { get; set; }
        public Nullable<long> SCAMAX { get; set; }
        public Nullable<long> SCAMIN { get; set; }
        public string TXTDSC { get; set; }
        public string RECDAT { get; set; }
        public string RECIND { get; set; }
        public string SORDAT { get; set; }
        public string SORIND { get; set; }
        public Nullable<float> SHAPE_Leng { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
    }
}
