//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_transect_l
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public geo_transect_l()
        {
            this.db_ed_donnees_gisement = new HashSet<db_ed_donnees_gisement>();
        }
    
        public int id_geo_transect_l { get; set; }
        public Nullable<int> id_tr_reference { get; set; }
        public Nullable<int> id_geo_banc_coquillier_s { get; set; }
        public string lieu { get; set; }
        public string nom_station { get; set; }
        public Nullable<double> x_debut { get; set; }
        public Nullable<double> y_debut { get; set; }
        public Nullable<double> x_fin { get; set; }
        public Nullable<double> y_fin { get; set; }
        public Nullable<double> zone_utm { get; set; }
        public string commentaire { get; set; }
        public byte[] geometry { get; set; }
        public Nullable<decimal> x_min { get; set; }
        public Nullable<decimal> y_min { get; set; }
        public Nullable<decimal> x_max { get; set; }
        public Nullable<decimal> y_max { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_ed_donnees_gisement> db_ed_donnees_gisement { get; set; }
        public virtual geo_banc_coquillier_s geo_banc_coquillier_s { get; set; }
        public virtual tr_reference tr_reference { get; set; }
    }
}
