//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_terrain_l_s
    {
        public int id_geo_terrain_l_s { get; set; }
        public Nullable<System.DateTime> date_terrain { get; set; }
        public string auteur { get; set; }
        public string type { get; set; }
        public string commentaire { get; set; }
        public byte[] geometry { get; set; }
        public Nullable<decimal> x_min { get; set; }
        public Nullable<decimal> y_min { get; set; }
        public Nullable<decimal> x_max { get; set; }
        public Nullable<decimal> y_max { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
    }
}
