//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_pollution_baie_gaspe_p
    {
        public double id_pollution_baie_gaspe_p { get; set; }
        public Nullable<System.DateTime> date_pollution { get; set; }
        public string poll_type { get; set; }
        public Nullable<double> categorie1 { get; set; }
        public Nullable<double> categorie2 { get; set; }
        public Nullable<double> categorie3 { get; set; }
        public string description { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<double> y { get; set; }
        public Nullable<double> x { get; set; }
    }
}
