//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_stations_p_resultat_tableau_2
    {
        public int id_geo_stations_p_resultat_tableau_2 { get; set; }
        public string secteur { get; set; }
        public Nullable<int> station { get; set; }
        public Nullable<decimal> mediane { get; set; }
        public Nullable<decimal> centile90 { get; set; }
        public Nullable<decimal> pourcent43 { get; set; }
        public Nullable<decimal> pourcent260 { get; set; }
        public Nullable<System.DateTime> dernier_calcul { get; set; }
    }
}
