//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupe_secteur
    {
        public int groupe_secteur_id { get; set; }
        public Nullable<int> groupe_id { get; set; }
        public Nullable<int> secteur_id { get; set; }
        public Nullable<int> etat { get; set; }
    
        public virtual secteur secteur { get; set; }
        public virtual secteur secteur1 { get; set; }
    }
}
