//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class hyperlien
    {
        public int hyperlien_ID { get; set; }
        public Nullable<int> CODIFICATION_ID { get; set; }
        public string URL_FR { get; set; }
        public string URL_EN { get; set; }
        public string DESCRIPTION_EN { get; set; }
        public string DESCRIPTION_FR { get; set; }
    
        public virtual codification codification { get; set; }
    }
}
