//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inf_Municipalite
    {
        public int ID_muni { get; set; }
        public Nullable<int> ID_Infrastructures { get; set; }
        public string Nom_muni { get; set; }
        public Nullable<int> Population_desservie { get; set; }
        public Nullable<double> Pourcentage_desservie { get; set; }
    }
}
