//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inf_Reseau_l
    {
        public int ID_reseau_l { get; set; }
        public string commentaire { get; set; }
        public Nullable<int> ID_reseau { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
        public string rue { get; set; }
        public string type_reseau { get; set; }
        public string dimension { get; set; }
        public string materieaux { get; set; }
        public string annee_construction { get; set; }
        public string service_type { get; set; }
    }
}
