//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inf_TypeEntite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inf_TypeEntite()
        {
            this.cour_zone_etude = new HashSet<cour_zone_etude>();
            this.cour_zone_etude1 = new HashSet<cour_zone_etude>();
            this.Inf_Infrastructures = new HashSet<Inf_Infrastructures>();
            this.Inf_Reseau = new HashSet<Inf_Reseau>();
            this.mod_contamination_s = new HashSet<mod_contamination_s>();
        }
    
        public int ID_TypeEntite { get; set; }
        public string Nom_Fr { get; set; }
        public string Nom_An { get; set; }
        public string Acronym_Fr { get; set; }
        public string Acronym_AN { get; set; }
        public string organisation { get; set; }
        public string parametre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cour_zone_etude> cour_zone_etude { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cour_zone_etude> cour_zone_etude1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inf_Infrastructures> Inf_Infrastructures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inf_Reseau> Inf_Reseau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mod_contamination_s> mod_contamination_s { get; set; }
    }
}
