//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inf_Reseau
    {
        public int ID_reseau { get; set; }
        public Nullable<int> ID_Infrastructures { get; set; }
        public string Nom_reseau { get; set; }
        public Nullable<int> Type_reseau { get; set; }
        public Nullable<System.DateTime> Date_construction { get; set; }
        public Nullable<System.DateTime> Date_modification { get; set; }
        public string Description { get; set; }
        public string Description_diffusable { get; set; }
    
        public virtual Inf_TypeEntite Inf_TypeEntite { get; set; }
    }
}
