//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inf_Traitement
    {
        public int ID_Traitement { get; set; }
        public Nullable<int> ID_Infrastructures { get; set; }
        public Nullable<int> ID_TypeEntite { get; set; }
        public Nullable<int> EA_Nombre_cellule { get; set; }
        public Nullable<int> EA_Volume { get; set; }
        public Nullable<int> EA_Aerateur { get; set; }
        public Nullable<double> EA_Radier { get; set; }
    }
}
