//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class laboratoire_operateur
    {
        public laboratoire_operateur()
        {
            this.db_tournee = new HashSet<db_tournee>();
        }
    
        public int laboratoire_operateur_id { get; set; }
        public Nullable<int> laboratoire { get; set; }
        public Nullable<int> compagnie { get; set; }
        public string nom_user_prism { get; set; }
    
        public virtual codification codification { get; set; }
        public virtual contact contact { get; set; }
        public virtual ICollection<db_tournee> db_tournee { get; set; }
    }
}
