//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class mammifere_marin_a_effacer
    {
        public string C_Date_ { get; set; }
        public string C_Emplacement_ { get; set; }
        public string C_Longitude_ { get; set; }
        public string C_Latitude_ { get; set; }
        public string C_Taxon_ { get; set; }
        public string C_Nom_Latin_ { get; set; }
        public string C_Nombre_d_individus_ { get; set; }
        public string C_Méthode_d_échantillonnage_ { get; set; }
        public string C_Collection_ { get; set; }
        public string C_Institution_propriétaire_ { get; set; }
        public Nullable<int> coordonnee_id { get; set; }
    }
}
