//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class maree
    {
        public int id_maree { get; set; }
        public Nullable<int> station { get; set; }
        public Nullable<System.DateTime> date_maree { get; set; }
        public Nullable<System.DateTime> date_heure_maree { get; set; }
        public Nullable<decimal> metre { get; set; }
        public string etale { get; set; }
        public string MM_GM { get; set; }
    }
}
