//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarineChartIndex
    {
        public int MarineChartID { get; set; }
        public string RasterID { get; set; }
        public string RASTER_DataFile { get; set; }
        public Nullable<float> AreaKm { get; set; }
        public string Location { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public string FirstNumberFolder { get; set; }
        public Nullable<int> Scale { get; set; }
        public string Datum { get; set; }
        public Nullable<int> CoordinateSystemsID { get; set; }
        public string UnitMeasure { get; set; }
        public string AvailableChart { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
    }
}
