//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class mod_contamination_s
    {
        public int id_mod_contamination_s { get; set; }
        public Nullable<int> id_modele { get; set; }
        public Nullable<int> duree_deversement { get; set; }
        public Nullable<int> contamination { get; set; }
        public string commentaire { get; set; }
    
        public virtual Inf_TypeEntite Inf_TypeEntite { get; set; }
        public virtual modele modele { get; set; }
    }
}
