//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class modele_contamination_s
    {
        public int id_mod_contamination_s { get; set; }
        public Nullable<int> id_modele_carto { get; set; }
        public Nullable<int> deversement { get; set; }
        public Nullable<int> contamination { get; set; }
        public string description { get; set; }
        public Nullable<int> ID_Infrastructures_rejet { get; set; }
        public Nullable<int> ID_Infrastructures_source { get; set; }
        public Nullable<int> ID_reseau { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
