//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipalite
    {
        public string NOM_ENTITE { get; set; }
        public string SNRC { get; set; }
        public Nullable<int> EDITION { get; set; }
        public Nullable<int> VERSION { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> CODE_GENER { get; set; }
        public Nullable<int> ATC { get; set; }
        public Nullable<int> ATG { get; set; }
        public Nullable<int> ATZ { get; set; }
        public Nullable<int> ATE { get; set; }
        public Nullable<int> PRECISION { get; set; }
        public string NOM_ADM { get; set; }
        public string ID_ADM { get; set; }
        public string TYPE_ADM { get; set; }
        public string ID_PROV { get; set; }
        public string ID_MUN_RMR { get; set; }
        public Nullable<int> ELEVATION { get; set; }
        public Nullable<double> CoorX { get; set; }
        public Nullable<double> CoorY { get; set; }
    }
}
