//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkID
    {
        public int EntityID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> EntityTypeID { get; set; }
        public Nullable<int> NetworkID1 { get; set; }
    }
}
