//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class No_Civ_region_ll83mdb
    {
        public int MAPINFO_ID { get; set; }
        public Nullable<double> Featureid { get; set; }
        public Nullable<double> Zorder { get; set; }
        public Nullable<double> Annotation { get; set; }
        public Nullable<double> Symbolid { get; set; }
        public Nullable<double> Status { get; set; }
        public string Textstri0 { get; set; }
        public string Fontname { get; set; }
        public Nullable<double> Fontsize { get; set; }
        public Nullable<double> Bold { get; set; }
        public Nullable<double> Italic { get; set; }
        public Nullable<double> Underline { get; set; }
        public Nullable<double> Verticalal { get; set; }
        public Nullable<double> Horizontal { get; set; }
        public Nullable<double> Xoffset { get; set; }
        public Nullable<double> Yoffset { get; set; }
        public Nullable<double> Angle { get; set; }
        public Nullable<double> Fontleadin { get; set; }
        public Nullable<double> Wordspacin { get; set; }
        public Nullable<double> Characterw { get; set; }
        public Nullable<double> Characters { get; set; }
        public Nullable<double> Flipangle { get; set; }
        public Nullable<double> Override { get; set; }
        public string Id_mat_civ { get; set; }
        public string Num_adr { get; set; }
        public string Lettre_adr { get; set; }
        public string Echelle { get; set; }
        public Nullable<double> Fontsize_t { get; set; }
        public Nullable<double> Va { get; set; }
        public Nullable<double> Ha { get; set; }
        public Nullable<double> Shape_leng { get; set; }
        public Nullable<double> Shape_area { get; set; }
        public Nullable<double> y { get; set; }
        public Nullable<double> x { get; set; }
    }
}
