//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class occ_idm_pour_tableau_v2
    {
        public int Ids { get; set; }
        public string TYPECOUV { get; set; }
        public string COUVERMETA { get; set; }
        public string DATECRE { get; set; }
        public string IDN { get; set; }
        public string FOURNISSR { get; set; }
        public string NOMJEUDONN { get; set; }
        public string PRECISION { get; set; }
        public string TECHACQ { get; set; }
        public string sup_m2 { get; set; }
        public Nullable<long> id { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
    }
}
