//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCCSM_CSSP_Tools_ID
    {
        public int ID { get; set; }
        public Nullable<int> PCCSM_ID { get; set; }
        public Nullable<int> CSSP_Tools_ID { get; set; }
        public string THEME { get; set; }
    }
}
