//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pccsmEntities : DbContext
    {
        public pccsmEntities()
            : base("name=pccsmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C2013_Municipalité> C2013_Municipalité { get; set; }
        public DbSet<C2013_Toponymes_officiels> C2013_Toponymes_officiels { get; set; }
        public DbSet<C2013_TypesEntitesToponymiques> C2013_TypesEntitesToponymiques { get; set; }
        public DbSet<BV_N1H_S_old> BV_N1H_S_old { get; set; }
        public DbSet<BV_N1M_S> BV_N1M_S { get; set; }
        public DbSet<BV_N1M_S_occupation_sup> BV_N1M_S_occupation_sup { get; set; }
        public DbSet<calendrier> calendriers { get; set; }
        public DbSet<calendrier_lunaire> calendrier_lunaire { get; set; }
        public DbSet<CCG_Nav_Aid> CCG_Nav_Aid { get; set; }
        public DbSet<CHS_PIPSOL_line> CHS_PIPSOL_line { get; set; }
        public DbSet<CHS_sounding> CHS_sounding { get; set; }
        public DbSet<codification> codifications { get; set; }
        public DbSet<codification_description> codification_description { get; set; }
        public DbSet<contact> contacts { get; set; }
        public DbSet<contact_groupe> contact_groupe { get; set; }
        public DbSet<cour_flotteur_p> cour_flotteur_p { get; set; }
        public DbSet<cour_trajectoire_l> cour_trajectoire_l { get; set; }
        public DbSet<cour_zone_etude> cour_zone_etude { get; set; }
        public DbSet<db_banc_espece> db_banc_espece { get; set; }
        public DbSet<db_banc_espece_exploitation> db_banc_espece_exploitation { get; set; }
        public DbSet<db_banc_secteur> db_banc_secteur { get; set; }
        public DbSet<db_banc_source_info> db_banc_source_info { get; set; }
        public DbSet<db_depuration> db_depuration { get; set; }
        public DbSet<db_document> db_document { get; set; }
        public DbSet<db_ec_recommandation> db_ec_recommandation { get; set; }
        public DbSet<db_ec_recommandation_note> db_ec_recommandation_note { get; set; }
        public DbSet<db_echantillonnage_planification> db_echantillonnage_planification { get; set; }
        public DbSet<db_echantillonnage_planification_mensuelle> db_echantillonnage_planification_mensuelle { get; set; }
        public DbSet<db_ed_donnees_gisement> db_ed_donnees_gisement { get; set; }
        public DbSet<db_ed_echantillonnage> db_ed_echantillonnage { get; set; }
        public DbSet<db_ed_granulometrie> db_ed_granulometrie { get; set; }
        public DbSet<db_ed_taille> db_ed_taille { get; set; }
        public DbSet<db_feedback> db_feedback { get; set; }
        public DbSet<db_histo_operation> db_histo_operation { get; set; }
        public DbSet<db_log_terrain> db_log_terrain { get; set; }
        public DbSet<db_mesure> db_mesure { get; set; }
        public DbSet<db_rapport> db_rapport { get; set; }
        public DbSet<db_station_no_georef> db_station_no_georef { get; set; }
        public DbSet<db_tournee> db_tournee { get; set; }
        public DbSet<db_tournee_maree_temporaire> db_tournee_maree_temporaire { get; set; }
        public DbSet<db_tournee_maree_temporaire_validation> db_tournee_maree_temporaire_validation { get; set; }
        public DbSet<db_zone> db_zone { get; set; }
        public DbSet<db_zone_secteur_station_meteo> db_zone_secteur_station_meteo { get; set; }
        public DbSet<evaluation_risque> evaluation_risque { get; set; }
        public DbSet<EvaluationRisqueSecteur> EvaluationRisqueSecteurs { get; set; }
        public DbSet<geo_banc_coquillier_s> geo_banc_coquillier_s { get; set; }
        public DbSet<GEO_BANC_COQUILLIER_S_ZVALID999> GEO_BANC_COQUILLIER_S_ZVALID999 { get; set; }
        public DbSet<geo_BV_N1M_S> geo_BV_N1M_S { get; set; }
        public DbSet<geo_BV_N2M_S> geo_BV_N2M_S { get; set; }
        public DbSet<geo_ed_quadrat_p> geo_ed_quadrat_p { get; set; }
        public DbSet<geo_feedback_ap> geo_feedback_ap { get; set; }
        public DbSet<geo_photographie_p> geo_photographie_p { get; set; }
        public DbSet<geo_pollution_baie_gaspe_p> geo_pollution_baie_gaspe_p { get; set; }
        public DbSet<geo_pollution_p> geo_pollution_p { get; set; }
        public DbSet<geo_pollution_p_fosse_septique_gaspe> geo_pollution_p_fosse_septique_gaspe { get; set; }
        public DbSet<geo_ressource_coquillliere_s> geo_ressource_coquillliere_s { get; set; }
        public DbSet<geo_SCF_sauvagine> geo_SCF_sauvagine { get; set; }
        public DbSet<geo_secteur_s> geo_secteur_s { get; set; }
        public DbSet<geo_station_audit_p> geo_station_audit_p { get; set; }
        public DbSet<geo_stations_p> geo_stations_p { get; set; }
        public DbSet<geo_terrain_l_s> geo_terrain_l_s { get; set; }
        public DbSet<geo_terrain_p> geo_terrain_p { get; set; }
        public DbSet<geo_transect_l> geo_transect_l { get; set; }
        public DbSet<geometry_columns> geometry_columns { get; set; }
        public DbSet<gps_log> gps_log { get; set; }
        public DbSet<hyperlien> hyperliens { get; set; }
        public DbSet<impact_evaluation> impact_evaluation { get; set; }
        public DbSet<Inf_Infrastructures> Inf_Infrastructures { get; set; }
        public DbSet<Inf_Municipalite> Inf_Municipalite { get; set; }
        public DbSet<Inf_Reseau> Inf_Reseau { get; set; }
        public DbSet<Inf_Traitement> Inf_Traitement { get; set; }
        public DbSet<Inf_TypeEntite> Inf_TypeEntite { get; set; }
        public DbSet<laboratoire_operateur> laboratoire_operateur { get; set; }
        public DbSet<mactre2012_inventaire_idm> mactre2012_inventaire_idm { get; set; }
        public DbSet<maree> marees { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<methode_description> methode_description { get; set; }
        public DbSet<mod_contamination_s> mod_contamination_s { get; set; }
        public DbSet<modele> modeles { get; set; }
        public DbSet<modele_dilution> modele_dilution { get; set; }
        public DbSet<municipalite> municipalites { get; set; }
        public DbSet<NetworkID> NetworkIDs { get; set; }
        public DbSet<No_Civ_region_ll83mdb> No_Civ_region_ll83mdb { get; set; }
        public DbSet<organisation> organisations { get; set; }
        public DbSet<PCCSM_CSSP_Tools_ID> PCCSM_CSSP_Tools_ID { get; set; }
        public DbSet<position_peche_espece_ziff> position_peche_espece_ziff { get; set; }
        public DbSet<QC_MRNF_SIEF_PEEFO> QC_MRNF_SIEF_PEEFO { get; set; }
        public DbSet<QC_MRNF_SIEF_PEEFO_CDR_CO> QC_MRNF_SIEF_PEEFO_CDR_CO { get; set; }
        public DbSet<QC_MRNF_SIEF_PEEFO_CLP_CO> QC_MRNF_SIEF_PEEFO_CLP_CO { get; set; }
        public DbSet<releve_sanitaire> releve_sanitaire { get; set; }
        public DbSet<releve_sanitaire_secteur> releve_sanitaire_secteur { get; set; }
        public DbSet<romm> romms { get; set; }
        public DbSet<romm_espece_code> romm_espece_code { get; set; }
        public DbSet<romm_observation> romm_observation { get; set; }
        public DbSet<RRN_QC_4_0_SEGMROUT> RRN_QC_4_0_SEGMROUT { get; set; }
        public DbSet<SCF_Colonies> SCF_Colonies { get; set; }
        public DbSet<SCF_Especes> SCF_Especes { get; set; }
        public DbSet<SCF_sauvagine_donnees_oiseaux> SCF_sauvagine_donnees_oiseaux { get; set; }
        public DbSet<SCF_sauvagine_DonneesOiseau_effacer> SCF_sauvagine_DonneesOiseau_effacer { get; set; }
        public DbSet<SCF_sauvagine_NoSEC_ZONE_effacer> SCF_sauvagine_NoSEC_ZONE_effacer { get; set; }
        public DbSet<spatial_ref_sys> spatial_ref_sys { get; set; }
        public DbSet<statcan_recensement_2011_lot> statcan_recensement_2011_lot { get; set; }
        public DbSet<statcan_recensement_2016_lot> statcan_recensement_2016_lot { get; set; }
        public DbSet<statcan_recensement_ilot> statcan_recensement_ilot { get; set; }
        public DbSet<station_climato_atl_qc> station_climato_atl_qc { get; set; }
        public DbSet<station_hydrometrique> station_hydrometrique { get; set; }
        public DbSet<station_hydrometrique_debit> station_hydrometrique_debit { get; set; }
        public DbSet<station_hydrometrique_secteur> station_hydrometrique_secteur { get; set; }
        public DbSet<station_maree> station_maree { get; set; }
        public DbSet<station_maree_moyenne_marnage> station_maree_moyenne_marnage { get; set; }
        public DbSet<station_maree_port_secondaire_diff> station_maree_port_secondaire_diff { get; set; }
        public DbSet<station_maree_secteur> station_maree_secteur { get; set; }
        public DbSet<station_meteo> station_meteo { get; set; }
        public DbSet<station_meteo_mddep> station_meteo_mddep { get; set; }
        public DbSet<station_meteo_precipitation_journaliere> station_meteo_precipitation_journaliere { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tblRapportTournee> tblRapportTournees { get; set; }
        public DbSet<temp_precipitation_journaliere> temp_precipitation_journaliere { get; set; }
        public DbSet<toponyme> toponymes { get; set; }
        public DbSet<tournee_planification> tournee_planification { get; set; }
        public DbSet<tr_agent_technique> tr_agent_technique { get; set; }
        public DbSet<tr_bearing> tr_bearing { get; set; }
        public DbSet<tr_code> tr_code { get; set; }
        public DbSet<tr_cueilleur> tr_cueilleur { get; set; }
        public DbSet<tr_espece> tr_espece { get; set; }
        public DbSet<tr_geo_pollution_baie_gaspe> tr_geo_pollution_baie_gaspe { get; set; }
        public DbSet<tr_geo_terrain> tr_geo_terrain { get; set; }
        public DbSet<tr_histo_type_operation> tr_histo_type_operation { get; set; }
        public DbSet<tr_llc_typecouv> tr_llc_typecouv { get; set; }
        public DbSet<tr_mer_etat> tr_mer_etat { get; set; }
        public DbSet<tr_ordonnance_type> tr_ordonnance_type { get; set; }
        public DbSet<tr_pollution_code> tr_pollution_code { get; set; }
        public DbSet<tr_recommandation> tr_recommandation { get; set; }
        public DbSet<tr_recommandation_mpo> tr_recommandation_mpo { get; set; }
        public DbSet<tr_reference> tr_reference { get; set; }
        public DbSet<tr_region_ordonnance_v1> tr_region_ordonnance_v1 { get; set; }
        public DbSet<tr_tr_code_type_entite_matrice> tr_tr_code_type_entite_matrice { get; set; }
        public DbSet<tributaire_par_secteur_par_annee> tributaire_par_secteur_par_annee { get; set; }
        public DbSet<waypoint> waypoints { get; set; }
        public DbSet<box_model_dilution_s> box_model_dilution_s { get; set; }
        public DbSet<db_ec_recommandation_local> db_ec_recommandation_local { get; set; }
        public DbSet<db_tournee_20171212> db_tournee_20171212 { get; set; }
        public DbSet<db_tournee_20180123> db_tournee_20180123 { get; set; }
        public DbSet<db_tournee_20180208_valeur_precipitation_3_jrs_ant_originale> db_tournee_20180208_valeur_precipitation_3_jrs_ant_originale { get; set; }
        public DbSet<dec> decs { get; set; }
        public DbSet<ec_Facility> ec_Facility { get; set; }
        public DbSet<geo_pollution_p_20180119> geo_pollution_p_20180119 { get; set; }
        public DbSet<MarineChartIndex> MarineChartIndexes { get; set; }
        public DbSet<SCF_BIOMQ> SCF_BIOMQ { get; set; }
        public DbSet<SCF_RivesPoints2> SCF_RivesPoints2 { get; set; }
        public DbSet<station_dans_buffer> station_dans_buffer { get; set; }
        public DbSet<station_meteo_precipitation_journaliere_20171212> station_meteo_precipitation_journaliere_20171212 { get; set; }
        public DbSet<temp_geo_stations_p> temp_geo_stations_p { get; set; }
        public DbSet<treaser> treasers { get; set; }
    }
}
