//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class position_peche_prevue_mactre_l
    {
        public int ID { get; set; }
        public string liste_des_points { get; set; }
        public string description { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
        public Nullable<int> annee { get; set; }
    }
}
