//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class position_peche_prevue_mactre
    {
        public int position_peche_prevue_mactre_id { get; set; }
        public string pecheur { get; set; }
        public string nom_du_secteur { get; set; }
        public string zone_ou_sous_zone { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<decimal> x { get; set; }
        public string date_visee { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
        public Nullable<int> annee { get; set; }
    }
}
