//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class position_peche_espece_ziff
    {
        public int position_peche_espece_ziff_id { get; set; }
        public string espece { get; set; }
        public Nullable<int> annee { get; set; }
        public Nullable<System.DateTime> date_capture { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
    }
}
