//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class position_peche_espece_ziff_l
    {
        public int id { get; set; }
        public Nullable<int> annee { get; set; }
        public string engin { get; set; }
        public string zone { get; set; }
        public Nullable<System.DateTime> date_capture { get; set; }
        public Nullable<decimal> lat_debut { get; set; }
        public Nullable<decimal> lon_debut { get; set; }
        public Nullable<decimal> lat_fin { get; set; }
        public Nullable<decimal> lon_fin { get; set; }
        public string origine { get; set; }
        public string espece { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
        public string gisement { get; set; }
    }
}
