//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_MRNF_SIEF_PEEFO_CDR_CO
    {
        public double CDR_CO { get; set; }
        public string CDR_DC { get; set; }
    }
}
