//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_MRNF_SIEF_PEEFO_CLP_CO
    {
        public string CLP_CO { get; set; }
        public string CLP_DC { get; set; }
        public string PENTE_MQEM { get; set; }
        public Nullable<int> min { get; set; }
        public Nullable<int> max { get; set; }
    }
}
