//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_MRNF_SIEF_PEEFO
    {
        public int MAPINFO_ID { get; set; }
        public Nullable<double> AREA { get; set; }
        public Nullable<double> PERIMETER { get; set; }
        public Nullable<double> C08PEEFC_ { get; set; }
        public Nullable<double> C08PEEFC_I { get; set; }
        public string FCA_NO { get; set; }
        public string GEOCODE { get; set; }
        public string PEE_DT_MJG { get; set; }
        public Nullable<double> PEE_SP_PEE { get; set; }
        public string PEE_GC_ORI { get; set; }
        public string PEE_NO_MAJ { get; set; }
        public string UCO_NO_UCO { get; set; }
        public string PEE_NO_AUC { get; set; }
        public string PEE_MD_AUC { get; set; }
        public string PEE_DT_MJU { get; set; }
        public string TOPONYME { get; set; }
        public string TCO_CO { get; set; }
        public string GES_CO { get; set; }
        public string PSC_CO { get; set; }
        public string CDE_CO { get; set; }
        public string CHA_CO { get; set; }
        public string PER_CO_ORI { get; set; }
        public string PER_AN_ORI { get; set; }
        public string CAG_CO { get; set; }
        public string PER_CO_MOY { get; set; }
        public string PEE_NB_INT { get; set; }
        public string PER_AN_MOY { get; set; }
        public string CLP_CO { get; set; }
        public string TER_CO { get; set; }
        public string DSU_CO { get; set; }
        public string RHY_CO { get; set; }
        public string CDR_CO { get; set; }
        public string TEC_CO_TEC { get; set; }
        public string PEE_DT_MJD { get; set; }
        public string EST_CO_ES1 { get; set; }
        public string EST_CO_PO1 { get; set; }
        public string EST_CO_ES2 { get; set; }
        public string EST_CO_PO2 { get; set; }
        public string PPR_CO_PPR { get; set; }
        public string PEE_DH_TRA { get; set; }
        public string PRB_CO_PRB { get; set; }
        public string PEE_VA_APP { get; set; }
        public string PEE_DC_MEO { get; set; }
        public string PHC_CO_PHC { get; set; }
        public string PEE_CO_ES1 { get; set; }
        public string PEE_CO_ES2 { get; set; }
        public string PEE_CO_ES3 { get; set; }
        public string PEE_CO_EP1 { get; set; }
        public string PEE_CO_EP2 { get; set; }
        public string PEE_CO_EP3 { get; set; }
        public string SER_CO_SER { get; set; }
        public string PEE_DC_AUT { get; set; }
        public Nullable<double> TVS_NO { get; set; }
        public Nullable<double> NO_ID { get; set; }
        public Nullable<double> NOG { get; set; }
        public string INDICATIF { get; set; }
        public string PEE_DH_CRE { get; set; }
        public string PEE_DH_MAJ { get; set; }
        public Nullable<double> TXL_NO_TXL { get; set; }
        public Nullable<double> MET_NO { get; set; }
        public string ETI_IN_GEN { get; set; }
    }
}
