//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class releve_sanitaire_secteur
    {
        public int releve_sanitaire_secteur_id { get; set; }
        public Nullable<int> releve_sanitaire_id { get; set; }
        public Nullable<int> secteur_id { get; set; }
        public string type_releve { get; set; }
        public string commentaire { get; set; }
    
        public virtual releve_sanitaire releve_sanitaire { get; set; }
    }
}
