//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class romm_observation
    {
        public int romm_observation_id { get; set; }
        public Nullable<int> romm_id { get; set; }
        public Nullable<int> @ref { get; set; }
        public string membre { get; set; }
        public Nullable<int> annee { get; set; }
        public Nullable<int> mois { get; set; }
        public Nullable<int> jour { get; set; }
        public Nullable<System.DateTime> date_obs { get; set; }
        public Nullable<System.DateTime> heure_obs { get; set; }
        public Nullable<int> obs { get; set; }
        public string espece_code { get; set; }
        public Nullable<int> cert { get; set; }
        public Nullable<int> nombre { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<decimal> x { get; set; }
    }
}
