//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class romm_espece_code
    {
        public int id { get; set; }
        public string espece_code { get; set; }
        public string espece_fr { get; set; }
        public string espece_latin { get; set; }
        public string espece_en { get; set; }
        public string statut { get; set; }
    }
}
