//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class romm
    {
        public romm()
        {
            this.romm_observation = new HashSet<romm_observation>();
        }
    
        public int romm_id { get; set; }
        public string membre { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<decimal> x { get; set; }
    
        public virtual ICollection<romm_observation> romm_observation { get; set; }
    }
}
