//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRN_QC_4_0_SEGMROUT
    {
        public string IDN { get; set; }
        public string NOMJEUDONN { get; set; }
        public string VERSNORMES { get; set; }
        public Nullable<decimal> PRECISION { get; set; }
        public string TECHACQ { get; set; }
        public string FOURNISSR { get; set; }
        public string DATECRE { get; set; }
        public string DATEREV { get; set; }
        public string COUVERMETA { get; set; }
        public string NUMSORTIE { get; set; }
        public decimal IDSEGMRTE { get; set; }
        public string IDINTERVAD { get; set; }
        public string CLASSROUTE { get; set; }
        public string NUMROUTE1 { get; set; }
        public string NUMROUTE2 { get; set; }
        public string NUMROUTE3 { get; set; }
        public string NUMROUTE4 { get; set; }
        public string NUMROUTE5 { get; set; }
        public string NOMRTE1FR { get; set; }
        public string NOMRTE2FR { get; set; }
        public string NOMRTE3FR { get; set; }
        public string NOMRTE4FR { get; set; }
        public string NOMRTE1AN { get; set; }
        public string NOMRTE2AN { get; set; }
        public string NOMRTE3AN { get; set; }
        public string NOMRTE4AN { get; set; }
        public Nullable<decimal> NBRVOIES { get; set; }
        public string ETATREV { get; set; }
        public string TYPEREV { get; set; }
        public string TYPENONREV { get; set; }
        public string IDSTRUCT { get; set; }
        public string TYPESTRUCT { get; set; }
        public string NOMSTRUCFR { get; set; }
        public string NOMSTRUCAN { get; set; }
        public string ADRSENS_G { get; set; }
        public Nullable<decimal> NUMP_G { get; set; }
        public Nullable<decimal> NUMD_G { get; set; }
        public string NOMRUE_C_G { get; set; }
        public string NOMLIEU_G { get; set; }
        public string ADRSENS_D { get; set; }
        public Nullable<decimal> NUMP_D { get; set; }
        public Nullable<decimal> NUMD_D { get; set; }
        public string NOMRUE_C_D { get; set; }
        public string NOMLIEU_D { get; set; }
    }
}
