//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCF_sauvagine_donnees_oiseaux
    {
        public int Id { get; set; }
        public string ESPECE_FR { get; set; }
        public string ESPECE_EN { get; set; }
        public Nullable<double> NOMBRE { get; set; }
        public Nullable<double> ANNEE { get; set; }
        public Nullable<double> MOIS { get; set; }
        public Nullable<double> JOUR { get; set; }
        public string SEC_ZONE { get; set; }
        public string SOURCE { get; set; }
        public string NOTICE_BIB { get; set; }
    }
}
