//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCF_sauvagine_DonneesOiseau_effacer
    {
        public int SCF_sauvagine_DonneesOiseauID { get; set; }
        public string ESPECE_FR { get; set; }
        public Nullable<int> NOMBRE { get; set; }
        public Nullable<int> ANNEE { get; set; }
        public Nullable<int> MOIS { get; set; }
        public Nullable<int> JOUR { get; set; }
        public Nullable<int> SEC_ZONE { get; set; }
        public string NOTICE_BIB { get; set; }
    }
}
