//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCF_Especes
    {
        public SCF_Especes()
        {
            this.SCF_BIOMQ = new HashSet<SCF_BIOMQ>();
        }
    
        public int Id_Espece { get; set; }
        public string Nom_Espece_fr { get; set; }
        public string Nom_Espece_en { get; set; }
        public string Nom_Espece_latin { get; set; }
        public Nullable<int> Id_TypePublication { get; set; }
        public int MAPINFO_ID { get; set; }
    
        public virtual ICollection<SCF_BIOMQ> SCF_BIOMQ { get; set; }
    }
}
