//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCF_Colonies
    {
        public SCF_Colonies()
        {
            this.SCF_BIOMQ = new HashSet<SCF_BIOMQ>();
        }
    
        public int Id_Colonie { get; set; }
        public string Nom_Colonie { get; set; }
        public bool Active { get; set; }
        public string Id_ZonePeche { get; set; }
        public Nullable<int> Id_Province { get; set; }
        public Nullable<double> CentroideX { get; set; }
        public Nullable<double> CentroideY { get; set; }
        public string CartesTopographiques { get; set; }
        public int MAPINFO_ID { get; set; }
    
        public virtual ICollection<SCF_BIOMQ> SCF_BIOMQ { get; set; }
    }
}
