//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class secteur
    {
        public int secteur_id { get; set; }
        public System.Guid globalID { get; set; }
        public Nullable<int> secteur_id_parent { get; set; }
        public string secteur1 { get; set; }
        public string secteur_ltr { get; set; }
        public Nullable<int> secteur_no1 { get; set; }
        public Nullable<int> secteur_no2 { get; set; }
        public Nullable<int> secteur_no3 { get; set; }
        public Nullable<int> secteur_no4 { get; set; }
        public Nullable<decimal> longueur_rive { get; set; }
        public Nullable<decimal> superficie { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<decimal> x_min { get; set; }
        public Nullable<decimal> y_min { get; set; }
        public Nullable<decimal> x_max { get; set; }
        public Nullable<decimal> y_max { get; set; }
        public Nullable<int> secteur_type { get; set; }
        public Nullable<int> etat { get; set; }
        public Nullable<bool> assujetti_pccsm { get; set; }
        public string description { get; set; }
        public Nullable<decimal> area { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
    }
}
