//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class secteur_epsg3857
    {
        public int secteur_id { get; set; }
        public Nullable<double> x_min { get; set; }
        public Nullable<double> x_max { get; set; }
        public Nullable<double> y_min { get; set; }
        public Nullable<double> y_max { get; set; }
    }
}
