//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class statcan_recensement_2011_lot
    {
        public string IDidu { get; set; }
        public Nullable<int> IDpop2011 { get; set; }
        public Nullable<int> IDtlog201 { get; set; }
        public Nullable<int> IDrh2011 { get; set; }
        public Nullable<decimal> IDsup { get; set; }
    }
}
