//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class station_maree_moyenne_marnage
    {
        public int station_meree_marnage_ID { get; set; }
        public Nullable<int> station { get; set; }
        public Nullable<int> annee { get; set; }
        public Nullable<decimal> marnage_maree_moyenne_m { get; set; }
        public Nullable<decimal> marnage_grande_maree_m { get; set; }
        public Nullable<decimal> mh_maree_moyenne_metre { get; set; }
        public Nullable<decimal> mh_grande_maree_metre { get; set; }
        public Nullable<decimal> mb_maree_moyenne_metre { get; set; }
        public Nullable<decimal> mb_grande_maree_metre { get; set; }
    }
}
