//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class station_maree_secteur
    {
        public int station_meree_secteur_id { get; set; }
        public string zone_e { get; set; }
        public string secteur { get; set; }
        public int annee { get; set; }
        public Nullable<int> PortSecondaireID { get; set; }
        public Nullable<int> PortSecondaireIntermediaireID { get; set; }
        public string Commentaire { get; set; }
        public Nullable<decimal> ajustement { get; set; }
        public Nullable<decimal> moyenne_marnage_pondere { get; set; }
        public string port_microbiolca { get; set; }
    }
}
