//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class station_meteo_mddep
    {
        public string no_station { get; set; }
        public string nom_station { get; set; }
        public Nullable<double> y { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> altitude { get; set; }
        public Nullable<int> no_seq_station { get; set; }
        public Nullable<int> poste { get; set; }
        public Nullable<System.DateTime> ouverture { get; set; }
        public Nullable<int> Pluviometre_a_auget { get; set; }
    }
}
