//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class statcan_recensement_ilot
    {
        public int statcan_recensement_ilot_ID { get; set; }
        public string IDidu { get; set; }
        public Nullable<int> annee { get; set; }
        public Nullable<double> IDpop { get; set; }
        public Nullable<double> IDtlog { get; set; }
        public Nullable<double> IDrh { get; set; }
        public Nullable<double> IDsup { get; set; }
        public string IDri { get; set; }
        public string ADidu { get; set; }
        public Nullable<double> ADlamx { get; set; }
        public Nullable<double> ADlamy { get; set; }
        public Nullable<double> ADlat { get; set; }
        public Nullable<double> ADlong { get; set; }
        public string PRidu { get; set; }
    }
}
