//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class station_climato_atl_qc
    {
        public string ID { get; set; }
        public string Station { get; set; }
        public Nullable<float> y { get; set; }
        public Nullable<float> x { get; set; }
    }
}
