//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class station_maree
    {
        public int Station { get; set; }
        public Nullable<int> PortDeReferenceID { get; set; }
        public string PortDeReference { get; set; }
        public string Localite { get; set; }
        public string province { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<bool> Prevision { get; set; }
        public bool prediction { get; set; }
    }
}
