//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class station_meteo
    {
        public int ID { get; set; }
        public string station { get; set; }
        public string nom { get; set; }
        public string proprietaire { get; set; }
        public string Commentaire { get; set; }
        public string climat { get; set; }
        public string tc { get; set; }
        public Nullable<int> omm { get; set; }
        public string mddep { get; set; }
        public Nullable<int> climatoID { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
        public Nullable<int> IdentificationStation { get; set; }
    }
}
