//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRapportTournee
    {
        public int ID { get; set; }
        public string USAGER { get; set; }
        public string ZONE_E { get; set; }
        public Nullable<int> ANNEE { get; set; }
        public Nullable<int> TOURNEE { get; set; }
        public Nullable<int> id_geo_station_p { get; set; }
        public Nullable<int> STATION { get; set; }
        public Nullable<int> MOIS { get; set; }
        public Nullable<int> JOUR { get; set; }
        public Nullable<int> CF { get; set; }
        public Nullable<int> NBR_TOURNEES { get; set; }
        public Nullable<int> MEDIANE_SPATIAL { get; set; }
        public Nullable<int> NPP43_SPATIAL { get; set; }
        public Nullable<int> PERC90_SPATIAL { get; set; }
    }
}
