//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_mactre_station_max_annee
    {
        public int id_geo_station_p { get; set; }
        public string secteur { get; set; }
        public Nullable<int> station { get; set; }
        public Nullable<int> max_annee { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
    }
}
