//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_geo_stations_p
    {
        public int id_geo_station_p { get; set; }
        public Nullable<int> station { get; set; }
        public string zone_e { get; set; }
        public string zone_limitrophe { get; set; }
        public string secteur { get; set; }
        public string secteur_limitrophe { get; set; }
        public string region { get; set; }
        public string type_station { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public string status { get; set; }
        public Nullable<bool> station_repere { get; set; }
        public string repere_visuel { get; set; }
        public Nullable<decimal> profondeur { get; set; }
        public string commentaire { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public System.Data.Entity.Spatial.DbGeography geographie { get; set; }
        public Nullable<decimal> x_deplacement { get; set; }
        public Nullable<decimal> y_deplacement { get; set; }
        public Nullable<System.DateTime> dernier_calcul { get; set; }
        public Nullable<decimal> mediane_15_tournee { get; set; }
        public Nullable<decimal> mediane_5_tourrnee { get; set; }
        public Nullable<decimal> pourcentage_43_15_tournee { get; set; }
        public Nullable<decimal> pourcentage_43_5_tournee { get; set; }
    }
}
