//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_precipitation_journaliere
    {
        public int ID { get; set; }
        public string station { get; set; }
        public Nullable<int> annee { get; set; }
        public Nullable<int> Mois { get; set; }
        public Nullable<int> jour { get; set; }
        public Nullable<int> Statut { get; set; }
        public Nullable<double> tempMax { get; set; }
        public Nullable<int> tempMaxStatut { get; set; }
        public Nullable<double> tempMin { get; set; }
        public Nullable<int> tempMinStatut { get; set; }
        public Nullable<double> PluieQ { get; set; }
        public Nullable<int> PluieQStatut { get; set; }
        public Nullable<double> NeigeQ { get; set; }
        public Nullable<int> NeigeQStatut { get; set; }
        public Nullable<double> PrecipitationQ { get; set; }
        public Nullable<int> PrecipitationQStatut { get; set; }
        public Nullable<double> NeigeDemain { get; set; }
        public Nullable<int> NeigeDemainStatut { get; set; }
        public Nullable<int> BrouillardBrume { get; set; }
        public Nullable<int> Giboulee { get; set; }
        public Nullable<int> Grele { get; set; }
        public Nullable<int> OrageTonnerre { get; set; }
        public Nullable<int> Poudrerie { get; set; }
        public Nullable<int> VentViolent { get; set; }
        public Nullable<int> Verglas { get; set; }
        public Nullable<int> Visibilite { get; set; }
    }
}
