//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_date_format
    {
        public int id { get; set; }
        public Nullable<System.DateTime> test_date { get; set; }
        public Nullable<System.DateTime> test_date_time { get; set; }
        public Nullable<System.DateTime> test_date_time2 { get; set; }
        public Nullable<System.DateTimeOffset> test_date_time_offset { get; set; }
        public Nullable<System.DateTime> test_smalldatetime { get; set; }
        public Nullable<System.TimeSpan> test_time { get; set; }
    }
}
