//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_agent_technique
    {
        public int id_agent_technique { get; set; }
        public string agent_technique { get; set; }
        public string telprofessionnel { get; set; }
        public string agent_titre { get; set; }
        public string agent_region { get; set; }
    }
}
