//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_bearing
    {
        public string bearing { get; set; }
        public Nullable<int> heading { get; set; }
        public string direction_fr { get; set; }
        public string direction_en { get; set; }
    }
}
