//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_cueilleur
    {
        public int id_tr_cueilleur { get; set; }
        public Nullable<int> no_cueilleur { get; set; }
        public string prenom { get; set; }
        public string nomfamille { get; set; }
        public string nas { get; set; }
        public string adresse { get; set; }
        public string ville { get; set; }
        public string province { get; set; }
        public string codepostal { get; set; }
        public string nomsociete { get; set; }
        public string titre { get; set; }
        public string telprofessionnel { get; set; }
        public string postetravail { get; set; }
        public string telephonemobile { get; set; }
        public string numtelecopie { get; set; }
        public string nomcourrierelec { get; set; }
        public string remarques { get; set; }
        public byte[] upsize_ts { get; set; }
        public string type { get; set; }
    }
}
