//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_espece
    {
        public tr_espece()
        {
            this.db_banc_espece = new HashSet<db_banc_espece>();
            this.db_ed_donnees_gisement = new HashSet<db_ed_donnees_gisement>();
        }
    
        public int id_tr_espece { get; set; }
        public string espece_fr { get; set; }
        public string espece_en { get; set; }
        public string espece_latin { get; set; }
        public string nom_commun_regional { get; set; }
    
        public virtual ICollection<db_banc_espece> db_banc_espece { get; set; }
        public virtual ICollection<db_ed_donnees_gisement> db_ed_donnees_gisement { get; set; }
    }
}
