//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_geo_terrain
    {
        public string code { get; set; }
        public string categorie { get; set; }
        public string symbolStyle { get; set; }
        public string fichier { get; set; }
        public byte[] Symbole { get; set; }
        public string waypoint_prefix { get; set; }
        public string waypoint_symbol { get; set; }
    }
}
