//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_llc_typecouv
    {
        public int typecouv { get; set; }
        public string etiquette { get; set; }
        public string definition { get; set; }
        public string propension_ruissellement { get; set; }
    }
}
