//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_ordonnance_type
    {
        public int id_ordonnance_type { get; set; }
        public string ordonnance_type { get; set; }
        public string description_fr { get; set; }
        public string description_en { get; set; }
    }
}
