//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_region_ordonnance_v1
    {
        public string region { get; set; }
        public string region_o { get; set; }
        public string region_a { get; set; }
        public string texte_region { get; set; }
        public string texte_region_a { get; set; }
        public string Preposition { get; set; }
        public string Preposition_en { get; set; }
    }
}
