//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_reference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tr_reference()
        {
            this.cour_zone_etude = new HashSet<cour_zone_etude>();
            this.db_banc_source_info = new HashSet<db_banc_source_info>();
            this.db_ed_echantillonnage = new HashSet<db_ed_echantillonnage>();
            this.geo_ed_quadrat_p = new HashSet<geo_ed_quadrat_p>();
            this.geo_transect_l = new HashSet<geo_transect_l>();
        }
    
        public int id_tr_reference { get; set; }
        public string reference { get; set; }
        public string reference_complete { get; set; }
        public string sujet { get; set; }
        public Nullable<bool> ref_format_papier { get; set; }
        public Nullable<bool> ref_format_electronique { get; set; }
        public string URL { get; set; }
        public string bibliotheque { get; set; }
        public string commentaire { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cour_zone_etude> cour_zone_etude { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_banc_source_info> db_banc_source_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_ed_echantillonnage> db_ed_echantillonnage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<geo_ed_quadrat_p> geo_ed_quadrat_p { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<geo_transect_l> geo_transect_l { get; set; }
    }
}
