//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_recommandation
    {
        public int id_tr_recommandation { get; set; }
        public string recommandation_fr { get; set; }
        public string recommandation_en { get; set; }
        public string recommandation_code { get; set; }
    }
}
