//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class waypoint
    {
        public int waypoint_ID { get; set; }
        public string name { get; set; }
        public Nullable<int> id_geo_station_p { get; set; }
        public Nullable<decimal> distance_mapinfo { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<System.DateTime> localDatetime { get; set; }
        public string usager { get; set; }
        public string description { get; set; }
    }
}
