//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldASGAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADSampleCode
    {
        public string SampCode { get; set; }
        public string OthCode { get; set; }
        public string SampName { get; set; }
        public string Units { get; set; }
        public Nullable<double> LowLimit { get; set; }
        public Nullable<double> HighLimit { get; set; }
    }
}
