//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldASGAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADSubsecDefPrecipStation
    {
        public ASGADSubsecDefPrecipStation()
        {
            this.ASGADDefPrecipStations = new HashSet<ASGADDefPrecipStation>();
        }
    
        public int SubsecDefPrecStaId { get; set; }
        public int SubsectorId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<ASGADDefPrecipStation> ASGADDefPrecipStations { get; set; }
        public virtual ASGADSubsector ASGADSubsector { get; set; }
    }
}
