//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldASGAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADSubsector
    {
        public ASGADSubsector()
        {
            this.ASGADRuns = new HashSet<ASGADRun>();
            this.ASGADStations = new HashSet<ASGADStation>();
            this.ASGADSubsecDefPrecipStations = new HashSet<ASGADSubsecDefPrecipStation>();
        }
    
        public Nullable<int> CSSPItemId { get; set; }
        public int SubsectorId { get; set; }
        public string SubsectorHistoricKey { get; set; }
        public string SubsectorCode { get; set; }
        public string DfoCode { get; set; }
        public string SubsectorName { get; set; }
        public string SubsectorDesc { get; set; }
        public string Map { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    
        public virtual ICollection<ASGADRun> ASGADRuns { get; set; }
        public virtual ICollection<ASGADStation> ASGADStations { get; set; }
        public virtual ICollection<ASGADSubsecDefPrecipStation> ASGADSubsecDefPrecipStations { get; set; }
    }
}
