//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldASGAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADStation
    {
        public ASGADStation()
        {
            this.ASGADSamples = new HashSet<ASGADSample>();
        }
    
        public int StationID { get; set; }
        public int SubsectorId { get; set; }
        public string StationNumber { get; set; }
        public string StationName { get; set; }
        public string StationType { get; set; }
        public string SortOrder { get; set; }
        public int Zone { get; set; }
        public double Easting { get; set; }
        public double Northing { get; set; }
        public decimal Lat { get; set; }
        public decimal Long { get; set; }
        public bool Active { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual ICollection<ASGADSample> ASGADSamples { get; set; }
        public virtual ASGADSubsector ASGADSubsector { get; set; }
    }
}
