//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldASGAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADPrecipStation
    {
        public ASGADPrecipStation()
        {
            this.ASGADDefPrecipStations = new HashSet<ASGADDefPrecipStation>();
            this.ASGADPrecipValues = new HashSet<ASGADPrecipValue>();
            this.ASGADRuns = new HashSet<ASGADRun>();
        }
    
        public string PrecipStnCode { get; set; }
        public string PrecipStnName { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public decimal LatDeg { get; set; }
        public decimal LongDeg { get; set; }
        public int Elevation { get; set; }
    
        public virtual ICollection<ASGADDefPrecipStation> ASGADDefPrecipStations { get; set; }
        public virtual ICollection<ASGADPrecipValue> ASGADPrecipValues { get; set; }
        public virtual ICollection<ASGADRun> ASGADRuns { get; set; }
    }
}
