//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldASGAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADPrecipValue
    {
        public string PrecipStnCode { get; set; }
        public System.DateTime PrecipDate { get; set; }
        public decimal Precipitation { get; set; }
    
        public virtual ASGADPrecipStation ASGADPrecipStation { get; set; }
    }
}
