//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldASGAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADTide
    {
        public ASGADTide()
        {
            this.ASGADRuns = new HashSet<ASGADRun>();
            this.ASGADRuns1 = new HashSet<ASGADRun>();
        }
    
        public string TideCode { get; set; }
        public string TideName { get; set; }
    
        public virtual ICollection<ASGADRun> ASGADRuns { get; set; }
        public virtual ICollection<ASGADRun> ASGADRuns1 { get; set; }
    }
}
