//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldASGAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADDefPrecipStation
    {
        public int DefPreStaId { get; set; }
        public int SubsecDefPrecStaId { get; set; }
        public string PrecipStnCode { get; set; }
        public int SelectionOrder { get; set; }
    
        public virtual ASGADPrecipStation ASGADPrecipStation { get; set; }
        public virtual ASGADSubsecDefPrecipStation ASGADSubsecDefPrecipStation { get; set; }
    }
}
