//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldASGAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASGADRun
    {
        public ASGADRun()
        {
            this.ASGADSamples = new HashSet<ASGADSample>();
        }
    
        public int RunId { get; set; }
        public int SubsectorId { get; set; }
        public int RunNumber { get; set; }
        public Nullable<System.DateTime> RunStartDateTime { get; set; }
        public Nullable<System.DateTime> RunEndDateTime { get; set; }
        public string TideStartCode { get; set; }
        public string TideEndCode { get; set; }
        public Nullable<bool> Autocalc { get; set; }
        public string SelectedPrecipStnCode { get; set; }
        public Nullable<decimal> PPT24 { get; set; }
        public Nullable<decimal> PPT48 { get; set; }
        public Nullable<decimal> PPT72 { get; set; }
        public string Note { get; set; }
        public System.DateTime Updated { get; set; }
        public System.DateTime OldRunDate { get; set; }
        public string OldStartTime { get; set; }
        public string OldEndTime { get; set; }
    
        public virtual ASGADPrecipStation ASGADPrecipStation { get; set; }
        public virtual ASGADSubsector ASGADSubsector { get; set; }
        public virtual ASGADTide ASGADTide { get; set; }
        public virtual ASGADTide ASGADTide1 { get; set; }
        public virtual ICollection<ASGADSample> ASGADSamples { get; set; }
    }
}
