//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public int AreaID { get; set; }
        public Nullable<int> id { get; set; }
        public string Locator { get; set; }
        public string Locator_Name { get; set; }
        public string Date_Reevaluation { get; set; }
        public string Inspector { get; set; }
        public Nullable<System.DateTime> File_Annual_update { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
