//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.ContactInfos = new HashSet<ContactInfo>();
            this.ContactUserNames = new HashSet<ContactUserName>();
            this.ContactUserRoles = new HashSet<ContactUserRole>();
        }
    
        public int ContactID { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Initial { get; set; }
        public string WebName { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<ContactInfo> ContactInfos { get; set; }
        public virtual ICollection<ContactUserName> ContactUserNames { get; set; }
        public virtual ICollection<ContactUserRole> ContactUserRoles { get; set; }
    }
}
