//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUserRole
    {
        public int ContactUserRoleID { get; set; }
        public int ContactID { get; set; }
        public int UserRoleID { get; set; }
        public int UserRoleTableID { get; set; }
        public int UserRoleTypeID { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
