//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUserName
    {
        public int ContactUserNameID { get; set; }
        public int ContactID { get; set; }
        public string UserName { get; set; }
        public string UserPass { get; set; }
        public string UserPassSHA256 { get; set; }
        public string ConfirmPass { get; set; }
        public string LiveID { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
