//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public int ContactInfoID { get; set; }
        public int ContactID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> ProvStateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Address { get; set; }
        public string TelWork { get; set; }
        public string TelHome { get; set; }
        public string TelCell { get; set; }
        public string WorkEmail { get; set; }
        public string HomeEmail { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> YearOfBirth { get; set; }
        public Nullable<int> MonthOfBirth { get; set; }
        public Nullable<int> DBImageID { get; set; }
        public string ThemeName { get; set; }
        public string LocalHTMLPage { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
