//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSSPTypeItem
    {
        public CSSPTypeItem()
        {
            this.CSSPItems = new HashSet<CSSPItem>();
            this.CSSPTypeItemLanguages = new HashSet<CSSPTypeItemLanguage>();
            this.CSSPTypeItems1 = new HashSet<CSSPTypeItem>();
        }
    
        public int CSSPTypeItemID { get; set; }
        public Nullable<int> CSSPTypeParentID { get; set; }
        public string CSSPTypeText { get; set; }
        public string CSSPTypePath { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<CSSPItem> CSSPItems { get; set; }
        public virtual ICollection<CSSPTypeItemLanguage> CSSPTypeItemLanguages { get; set; }
        public virtual ICollection<CSSPTypeItem> CSSPTypeItems1 { get; set; }
        public virtual CSSPTypeItem CSSPTypeItem1 { get; set; }
    }
}
