//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSSPFile
    {
        public CSSPFile()
        {
            this.CSSPItemFiles = new HashSet<CSSPItemFile>();
            this.MikeBoundaryConditions = new HashSet<MikeBoundaryCondition>();
            this.MikeScenarioFiles = new HashSet<MikeScenarioFile>();
            this.MikeScenarioFiles1 = new HashSet<MikeScenarioFile>();
        }
    
        public int CSSPFileID { get; set; }
        public System.Guid CSSPGuid { get; set; }
        public string Purpose { get; set; }
        public string FileName { get; set; }
        public string FileOriginalPath { get; set; }
        public string FileDescription { get; set; }
        public byte[] FileContent { get; set; }
        public string FileType { get; set; }
        public Nullable<long> FileSize { get; set; }
        public Nullable<System.DateTime> FileCreatedDate { get; set; }
        public Nullable<System.DateTime> DataStartDate { get; set; }
        public Nullable<System.DateTime> DataEndDate { get; set; }
        public Nullable<double> TimeStepsInSecond { get; set; }
        public string ParameterNames { get; set; }
        public string ParameterUnits { get; set; }
        public Nullable<bool> IsCompressed { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<CSSPItemFile> CSSPItemFiles { get; set; }
        public virtual ICollection<MikeBoundaryCondition> MikeBoundaryConditions { get; set; }
        public virtual ICollection<MikeScenarioFile> MikeScenarioFiles { get; set; }
        public virtual ICollection<MikeScenarioFile> MikeScenarioFiles1 { get; set; }
    }
}
