//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBErrLog
    {
        public int DBErrLogID { get; set; }
        public string DBErrLogUniqueTag { get; set; }
        public int DBErrLogLineNumber { get; set; }
        public string DBErrLogSource { get; set; }
        public string DBErrLogMessage { get; set; }
        public System.DateTime DBErrLogDateTime { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
