//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class MikeBoundaryConditionValue
    {
        public int MikeBoundaryConditionID { get; set; }
        public System.DateTime ValueDateTime { get; set; }
        public Nullable<double> WaterLevel { get; set; }
        public Nullable<double> UVelocityComponent { get; set; }
        public Nullable<double> VVelocityComponent { get; set; }
    
        public virtual MikeBoundaryCondition MikeBoundaryCondition { get; set; }
    }
}
