//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class MikeBoundaryCondition
    {
        public MikeBoundaryCondition()
        {
            this.MikeBoundaryConditionValues = new HashSet<MikeBoundaryConditionValue>();
            this.MikeScenarioBoundaryConditions = new HashSet<MikeScenarioBoundaryCondition>();
        }
    
        public int MikeBoundaryConditionID { get; set; }
        public Nullable<int> CSSPFileID { get; set; }
        public string BoundaryConditionName { get; set; }
        public Nullable<double> StartLatitude { get; set; }
        public Nullable<double> StartLongitude { get; set; }
        public Nullable<double> EndLatitude { get; set; }
        public Nullable<double> EndLongitude { get; set; }
        public string MeasurementLocation { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual CSSPFile CSSPFile { get; set; }
        public virtual ICollection<MikeBoundaryConditionValue> MikeBoundaryConditionValues { get; set; }
        public virtual ICollection<MikeScenarioBoundaryCondition> MikeScenarioBoundaryConditions { get; set; }
    }
}
