//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoRunVPDBEntities : DbContext
    {
        public AutoRunVPDBEntities()
            : base("name=AutoRunVPDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aaTable> aaTables { get; set; }
        public DbSet<Ambient> Ambients { get; set; }
        public DbSet<Area> Areas { get; set; }
        public DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public DbSet<aspnet_Users> aspnet_Users { get; set; }
        public DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public DbSet<BoxModelResult> BoxModelResults { get; set; }
        public DbSet<BoxModel> BoxModels { get; set; }
        public DbSet<ContactInfo> ContactInfos { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<ContactUserName> ContactUserNames { get; set; }
        public DbSet<ContactUserRole> ContactUserRoles { get; set; }
        public DbSet<CSSPFile> CSSPFiles { get; set; }
        public DbSet<CSSPItemFile> CSSPItemFiles { get; set; }
        public DbSet<CSSPItemLanguage> CSSPItemLanguages { get; set; }
        public DbSet<CSSPItem> CSSPItems { get; set; }
        public DbSet<CSSPTypeItemLanguage> CSSPTypeItemLanguages { get; set; }
        public DbSet<CSSPTypeItem> CSSPTypeItems { get; set; }
        public DbSet<DBErrLog> DBErrLogs { get; set; }
        public DbSet<DBLog> DBLogs { get; set; }
        public DbSet<Infrastructure> Infrastructures { get; set; }
        public DbSet<MikeBoundaryCondition> MikeBoundaryConditions { get; set; }
        public DbSet<MikeBoundaryConditionValue> MikeBoundaryConditionValues { get; set; }
        public DbSet<MikeParameter> MikeParameters { get; set; }
        public DbSet<MikeScenarioBoundaryCondition> MikeScenarioBoundaryConditions { get; set; }
        public DbSet<MikeScenarioFile> MikeScenarioFiles { get; set; }
        public DbSet<MikeScenario> MikeScenarios { get; set; }
        public DbSet<MikeSource> MikeSources { get; set; }
        public DbSet<Observation> Observations { get; set; }
        public DbSet<PrecEmail> PrecEmails { get; set; }
        public DbSet<PrecProvince> PrecProvinces { get; set; }
        public DbSet<PrecStation> PrecStations { get; set; }
        public DbSet<RiskAssessment> RiskAssessments { get; set; }
        public DbSet<Sample> Samples { get; set; }
        public DbSet<SanitaryReport> SanitaryReports { get; set; }
        public DbSet<SanitaryType> SanitaryTypes { get; set; }
        public DbSet<Scenario> Scenarios { get; set; }
        public DbSet<SelectedCormixResult> SelectedCormixResults { get; set; }
        public DbSet<SelectedResult> SelectedResults { get; set; }
        public DbSet<ShellfishAreaCentroid> ShellfishAreaCentroids { get; set; }
        public DbSet<Site> Sites { get; set; }
        public DbSet<Spill> Spills { get; set; }
        public DbSet<StatusCode> StatusCodes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<ValuedCormixResult> ValuedCormixResults { get; set; }
        public DbSet<ValuedResult> ValuedResults { get; set; }
        public DbSet<WWTPSpec> WWTPSpecs { get; set; }
    }
}
