//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecProvince
    {
        public PrecProvince()
        {
            this.PrecEmails = new HashSet<PrecEmail>();
            this.PrecStations = new HashSet<PrecStation>();
        }
    
        public int PrecProvinceID { get; set; }
        public string ProvName { get; set; }
    
        public virtual ICollection<PrecEmail> PrecEmails { get; set; }
        public virtual ICollection<PrecStation> PrecStations { get; set; }
    }
}
