//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        public int SampleID { get; set; }
        public Nullable<int> TP_ID { get; set; }
        public Nullable<int> Sample_ID { get; set; }
        public string LOCATOR { get; set; }
        public string PLANT_NAME { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Sample_type { get; set; }
        public Nullable<float> Sample_value { get; set; }
        public string Sample_Pos { get; set; }
        public string Sample_Flag { get; set; }
        public string Sample_Comments { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
