//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scenario
    {
        public Scenario()
        {
            this.Ambients = new HashSet<Ambient>();
            this.SelectedCormixResults = new HashSet<SelectedCormixResult>();
            this.SelectedResults = new HashSet<SelectedResult>();
            this.ValuedCormixResults = new HashSet<ValuedCormixResult>();
            this.ValuedResults = new HashSet<ValuedResult>();
        }
    
        public int ScenarioID { get; set; }
        public int CSSPItemID { get; set; }
        public string ScenarioName { get; set; }
        public System.DateTime ScenarioDate { get; set; }
        public Nullable<bool> UseAsBestEstimate { get; set; }
        public double EffluentFlow { get; set; }
        public double EffluentConcentration { get; set; }
        public double FroudeNumber { get; set; }
        public double PortDiameter { get; set; }
        public double PortDepth { get; set; }
        public double PortElevation { get; set; }
        public double VerticalAngle { get; set; }
        public double HorizontalAngle { get; set; }
        public double NumberOfPorts { get; set; }
        public double PortSpacing { get; set; }
        public double AcuteMixZone { get; set; }
        public double ChronicMixZone { get; set; }
        public double EffluentSalinity { get; set; }
        public double EffluentTemperature { get; set; }
        public double EffluentVelocity { get; set; }
        public string RawResults { get; set; }
        public string ParsedResults { get; set; }
        public string CormixSummaryResults { get; set; }
        public string CormixDetailResults { get; set; }
        public string CormixParsedResults { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Ambient> Ambients { get; set; }
        public virtual CSSPItem CSSPItem { get; set; }
        public virtual ICollection<SelectedCormixResult> SelectedCormixResults { get; set; }
        public virtual ICollection<SelectedResult> SelectedResults { get; set; }
        public virtual ICollection<ValuedCormixResult> ValuedCormixResults { get; set; }
        public virtual ICollection<ValuedResult> ValuedResults { get; set; }
    }
}
