//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellfishAreaCentroid
    {
        public int ShellfishAreaCentroidID { get; set; }
        public Nullable<int> ID { get; set; }
        public string PROV { get; set; }
        public string AREA { get; set; }
        public string SECTOR { get; set; }
        public string SUBSECTOR { get; set; }
        public string NAME { get; set; }
        public string DESCRIPT { get; set; }
        public string SHELLFISH_AREA_LABEL { get; set; }
        public Nullable<float> LATITUDE_CENTROID { get; set; }
        public Nullable<float> LONGITUDE_CENTROID { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
