//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spill
    {
        public int SpillID { get; set; }
        public Nullable<int> spillNumber { get; set; }
        public string PROVINCE { get; set; }
        public Nullable<int> TP_ID { get; set; }
        public string Location { get; set; }
        public string documentation { get; set; }
        public Nullable<System.DateTime> Date_incident { get; set; }
        public Nullable<System.DateTime> Date_Incident_ended { get; set; }
        public string EST_FLOW { get; set; }
        public Nullable<bool> ActionRequired { get; set; }
        public string ActionComment { get; set; }
        public string ReceivingWater { get; set; }
        public Nullable<int> EST_FC { get; set; }
        public Nullable<int> EST_BOD { get; set; }
        public Nullable<int> EST_SS { get; set; }
        public string Contact { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
