//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValuedCormixResult
    {
        public int ScenarioID { get; set; }
        public int ArrayNum { get; set; }
        public double Concentration { get; set; }
        public double Dilution { get; set; }
        public double FarFieldWidth { get; set; }
        public double DispersionDistance { get; set; }
        public double TravelTime { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Scenario Scenario { get; set; }
    }
}
