//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldAutoRunVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class WWTPSpec
    {
        public int WWTPSpecID { get; set; }
        public Nullable<float> SITEID { get; set; }
        public Nullable<int> site { get; set; }
        public Nullable<System.DateTime> Date_Site { get; set; }
        public Nullable<float> LATITUDE { get; set; }
        public Nullable<float> LONGITUDE { get; set; }
        public string MUNICIPALITY_INDUSTRY { get; set; }
        public string TREATMENT_TYPE { get; set; }
        public Nullable<float> DESIGN_FLOW_m3_d { get; set; }
        public Nullable<float> ACTUAL_FLOW_m3_d { get; set; }
        public Nullable<float> DESIGN_POP { get; set; }
        public Nullable<float> ACTUAL_POP { get; set; }
        public Nullable<float> YEAR_CONST { get; set; }
        public string NAME_OPERATOR { get; set; }
        public string OPERATOR_PHONE { get; set; }
        public string DISINFECTION { get; set; }
        public Nullable<int> BOD_mg_l_influent { get; set; }
        public Nullable<int> SS_mg_l_influent { get; set; }
        public Nullable<int> BOD_mg_l_effluent { get; set; }
        public Nullable<int> SS_mg_l_effluent { get; set; }
        public Nullable<int> faecal_coli_mpn_100ml { get; set; }
        public Nullable<int> Chlorine_res_mg_l { get; set; }
        public Nullable<int> Oil_grease_mg_l { get; set; }
        public Nullable<decimal> ph { get; set; }
        public Nullable<int> phenol_mg_l { get; set; }
        public Nullable<int> total_Phosporous_mg_l { get; set; }
        public Nullable<int> MAPINFO_ID { get; set; }
        public string plant_images { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
