//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TempDataToolDBEntities : DbContext
    {
        public TempDataToolDBEntities()
            : base("name=TempDataToolDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ASGADMPNTable> ASGADMPNTables { get; set; }
        public DbSet<ASGADPrecData> ASGADPrecDatas { get; set; }
        public DbSet<ASGADPrecStn> ASGADPrecStns { get; set; }
        public DbSet<ASGADRunMOU> ASGADRunMOUs { get; set; }
        public DbSet<ASGADRun> ASGADRuns { get; set; }
        public DbSet<ASGADSampCode> ASGADSampCodes { get; set; }
        public DbSet<ASGADSampleMOU> ASGADSampleMOUs { get; set; }
        public DbSet<ASGADSample> ASGADSamples { get; set; }
        public DbSet<ASGADStation> ASGADStations { get; set; }
        public DbSet<ASGADSubsect> ASGADSubsects { get; set; }
        public DbSet<ASGADTide> ASGADTides { get; set; }
        public DbSet<BCLandSample> BCLandSamples { get; set; }
        public DbSet<BCLandSampleStation> BCLandSampleStations { get; set; }
        public DbSet<BCMarineSample> BCMarineSamples { get; set; }
        public DbSet<BCMarineSampleStation> BCMarineSampleStations { get; set; }
        public DbSet<BCName> BCNames { get; set; }
        public DbSet<BCPolSource> BCPolSources { get; set; }
        public DbSet<BCPrecipitation> BCPrecipitations { get; set; }
        public DbSet<BCSurvey> BCSurveys { get; set; }
        public DbSet<LocationNameLatLng> LocationNameLatLngs { get; set; }
        public DbSet<Nomenclature> Nomenclatures { get; set; }
        public DbSet<QCClimateSite> QCClimateSites { get; set; }
        public DbSet<QCSecteurMPol> QCSecteurMPols { get; set; }
        public DbSet<QCSubsectorAssociation> QCSubsectorAssociations { get; set; }
        public DbSet<QCSubSector> QCSubSectors { get; set; }
        public DbSet<SanitaryDavCOb> SanitaryDavCObs { get; set; }
        public DbSet<SanitaryDavCSite> SanitaryDavCSites { get; set; }
        public DbSet<SanitaryDavOb> SanitaryDavObs { get; set; }
        public DbSet<SanitaryDavSite> SanitaryDavSites { get; set; }
        public DbSet<SanitaryDonOb> SanitaryDonObs { get; set; }
        public DbSet<SanitaryDonSite> SanitaryDonSites { get; set; }
        public DbSet<SanitaryJoeOb> SanitaryJoeObs { get; set; }
        public DbSet<SanitaryJoeSite> SanitaryJoeSites { get; set; }
        public DbSet<SanitaryPatOb> SanitaryPatObs { get; set; }
        public DbSet<SanitaryPatSite> SanitaryPatSites { get; set; }
    }
}
