//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class clause
    {
        public clause()
        {
            this.clause_interdiction = new HashSet<clause_interdiction>();
            this.clause_methode = new HashSet<clause_methode>();
            this.clause_secteur = new HashSet<clause_secteur>();
            this.clause_espece = new HashSet<clause_espece>();
            this.clause_periode = new HashSet<clause_periode>();
        }
    
        public int clause_id { get; set; }
        public Nullable<int> ordonnance_id { get; set; }
        public Nullable<int> clause_type { get; set; }
        public Nullable<int> clause_no { get; set; }
    
        public virtual codification codification { get; set; }
        public virtual ICollection<clause_interdiction> clause_interdiction { get; set; }
        public virtual ICollection<clause_methode> clause_methode { get; set; }
        public virtual ICollection<clause_secteur> clause_secteur { get; set; }
        public virtual ICollection<clause_espece> clause_espece { get; set; }
        public virtual ICollection<clause_periode> clause_periode { get; set; }
        public virtual ordonnance ordonnance { get; set; }
    }
}
