//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public contact()
        {
            this.contact_communication = new HashSet<contact_communication>();
            this.contact_groupe = new HashSet<contact_groupe>();
            this.ordonnances = new HashSet<ordonnance>();
        }
    
        public int contact_id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public Nullable<int> organisation { get; set; }
        public Nullable<int> titre { get; set; }
        public string telephone { get; set; }
        public string cellulaire { get; set; }
        public string fax { get; set; }
        public string courriel { get; set; }
        public string adresse_postale { get; set; }
        public Nullable<int> ville { get; set; }
        public string code_postal { get; set; }
        public Nullable<int> province { get; set; }
        public string nom_user { get; set; }
        public string commentaire { get; set; }
        public Nullable<int> ID_Infra { get; set; }
        public Nullable<int> contact_primaire { get; set; }
        public Nullable<int> infrastrure_id { get; set; }
    
        public virtual codification codification { get; set; }
        public virtual codification codification1 { get; set; }
        public virtual codification codification2 { get; set; }
        public virtual codification codification3 { get; set; }
        public virtual ICollection<contact_communication> contact_communication { get; set; }
        public virtual ICollection<contact_groupe> contact_groupe { get; set; }
        public virtual ICollection<ordonnance> ordonnances { get; set; }
    }
}
