//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_communication
    {
        public int contact_communication_id { get; set; }
        public Nullable<int> communication { get; set; }
        public string communication_valeur { get; set; }
        public Nullable<int> contact_id { get; set; }
    
        public virtual codification codification { get; set; }
        public virtual contact contact { get; set; }
    }
}
