//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class echantillonnage_microbiol
    {
        public int id_echantillonnage_microbiol { get; set; }
        public Nullable<int> id_geo_pccsm_acia_station { get; set; }
        public Nullable<int> No_LSTS { get; set; }
        public string nom_especes_francais { get; set; }
        public string Cueilleur { get; set; }
        public Nullable<System.DateTime> echant_date { get; set; }
        public Nullable<System.DateTime> heure_cueillette { get; set; }
        public string Temperature_depart { get; set; }
        public Nullable<System.DateTime> Date_analyse { get; set; }
        public string Temperature_arrivee { get; set; }
        public Nullable<float> No_lab_micro { get; set; }
        public string resultat_col_fec { get; set; }
        public string Verdict_col_fec { get; set; }
        public string Remarque { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
