//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class echantillonnage_toxicite
    {
        public Nullable<int> id_geo_pccsm_acia_station { get; set; }
        public int Numero_id { get; set; }
        public string No_LSTS { get; set; }
        public string No_lab_PSP { get; set; }
        public string Sous_échantillon { get; set; }
        public string Nom_especes_francais { get; set; }
        public string Type_exploitation { get; set; }
        public string Secteurs { get; set; }
        public string Nom_secteur_francais { get; set; }
        public string Sous_secteur { get; set; }
        public string Cueilleur { get; set; }
        public Nullable<System.DateTime> Date_cueillette { get; set; }
        public string Heure_cueillette { get; set; }
        public string Code_usine { get; set; }
        public string Température_départ { get; set; }
        public Nullable<System.DateTime> Date_série { get; set; }
        public string Resultat_PSP_ug_100g { get; set; }
        public string Verdict_PSP { get; set; }
        public Nullable<short> Mortalite_souris { get; set; }
        public string Temperature_arrivee { get; set; }
        public string Frequence_Domoique { get; set; }
        public string No_lab_Longueuil { get; set; }
        public string Resultat_ASP { get; set; }
        public string Verdict_ASP { get; set; }
        public string Traitement_primaire { get; set; }
        public string Traitement_secondaire { get; set; }
        public string Traitement_tertiaire { get; set; }
        public string Tissus { get; set; }
        public string Remarque { get; set; }
        public bool Échantillon_Dartmouth { get; set; }
        public Nullable<System.DateTime> Date_analyse_DSP { get; set; }
        public string Resultats_DSP { get; set; }
        public string Verdict_DSP { get; set; }
        public string Pectenotoxin_2 { get; set; }
        public string Pect2_secoacid { get; set; }
        public string Pect2_sec_7epi { get; set; }
        public string Gymnodimine { get; set; }
        public string Dinophysis_toxin_3 { get; set; }
        public string Yessotoxin { get; set; }
        public string Okadoïques_totaux { get; set; }
        public string Pectenotoxines_totales { get; set; }
        public string Yessotoxines_totales { get; set; }
    }
}
