//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_segment_l
    {
        public int Id { get; set; }
        public Nullable<long> ID_SEGMENT { get; set; }
        public string SEG_NUMERO { get; set; }
    }
}
