//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class language
    {
        public int language_id { get; set; }
        public Nullable<int> langue { get; set; }
        public string page { get; set; }
        public string name { get; set; }
        public string LanguageText { get; set; }
    }
}
