//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class mrc
    {
        public int Id { get; set; }
        public Nullable<long> OBJECTID { get; set; }
        public Nullable<double> AREA { get; set; }
        public Nullable<double> PERIMETER { get; set; }
        public Nullable<long> MRC_S0_ { get; set; }
        public Nullable<long> MRC_S0_ID { get; set; }
        public string MRS_NO_IND { get; set; }
        public string MRS_DE_IND { get; set; }
        public string MRS_CO_MRC { get; set; }
        public string MRS_NM_MRC { get; set; }
        public string MRS_CO_REG { get; set; }
        public string MRS_NM_REG { get; set; }
        public string MRS_CO_REF { get; set; }
        public string MRS_CO_VER { get; set; }
        public Nullable<double> Shape_Leng { get; set; }
        public Nullable<double> Shape_Area { get; set; }
    }
}
