//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class munic
    {
        public int Id { get; set; }
        public Nullable<long> OBJECTID { get; set; }
        public Nullable<double> AREA { get; set; }
        public Nullable<double> PERIMETER { get; set; }
        public Nullable<long> MUNIC2013_ { get; set; }
        public Nullable<long> MUNIC20131 { get; set; }
        public Nullable<double> MUS_VA_SUP { get; set; }
        public string MUS_NO_IND { get; set; }
        public string MUS_DE_IND { get; set; }
        public string MUS_CO_GEO { get; set; }
        public string MUS_CO_DES { get; set; }
        public string MUS_NM_MUN { get; set; }
        public string MUS_CO_MRC { get; set; }
        public string MUS_NM_MRC { get; set; }
        public string MUS_CO_REG { get; set; }
        public string MUS_NM_REG { get; set; }
        public string MUS_NM_AGG { get; set; }
        public string MUS_NM_COM { get; set; }
        public string MUS_DA_CON { get; set; }
        public string MUS_CO_MOD { get; set; }
        public string MUS_DA_MOD { get; set; }
        public string MUS_CO_SOU { get; set; }
        public string MUS_CO_REF { get; set; }
        public string MUS_CO_VER { get; set; }
        public Nullable<double> Shape_Leng { get; set; }
        public Nullable<double> Shape_Area { get; set; }
    }
}
