//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordonnance
    {
        public ordonnance()
        {
            this.clauses = new HashSet<clause>();
            this.historique_operation = new HashSet<historique_operation>();
        }
    
        public int ordonnance_id { get; set; }
        public Nullable<int> abrogation_id { get; set; }
        public string ordonnance_no { get; set; }
        public Nullable<int> ordonnance_type { get; set; }
        public Nullable<int> etat { get; set; }
        public Nullable<System.DateTime> date_en_vigueur { get; set; }
        public Nullable<System.DateTime> date_abrogation { get; set; }
        public Nullable<int> raison { get; set; }
        public string communique { get; set; }
        public Nullable<int> ordonnance_signataire { get; set; }
        public Nullable<int> communique_signataire { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<clause> clauses { get; set; }
        public virtual codification codification { get; set; }
        public virtual codification codification1 { get; set; }
        public virtual codification codification2 { get; set; }
        public virtual contact contact { get; set; }
        public virtual ICollection<historique_operation> historique_operation { get; set; }
    }
}
