//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pccsm_mpoEntities : DbContext
    {
        public pccsm_mpoEntities()
            : base("name=pccsm_mpoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<clause> clauses { get; set; }
        public DbSet<clause_espece> clause_espece { get; set; }
        public DbSet<clause_interdiction> clause_interdiction { get; set; }
        public DbSet<clause_methode> clause_methode { get; set; }
        public DbSet<clause_periode> clause_periode { get; set; }
        public DbSet<clause_secteur> clause_secteur { get; set; }
        public DbSet<codification> codifications { get; set; }
        public DbSet<codification_description> codification_description { get; set; }
        public DbSet<contact> contacts { get; set; }
        public DbSet<contact_communication> contact_communication { get; set; }
        public DbSet<contact_groupe> contact_groupe { get; set; }
        public DbSet<db_histo_operation> db_histo_operation { get; set; }
        public DbSet<dtproperty> dtproperties { get; set; }
        public DbSet<groupe_secteur> groupe_secteur { get; set; }
        public DbSet<historique_operation> historique_operation { get; set; }
        public DbSet<language> languages { get; set; }
        public DbSet<ordonnance> ordonnances { get; set; }
        public DbSet<point_legal> point_legal { get; set; }
        public DbSet<secteur> secteurs { get; set; }
        public DbSet<secteur_description> secteur_description { get; set; }
        public DbSet<secteur_historique> secteur_historique { get; set; }
        public DbSet<secteur_point_archive> secteur_point_archive { get; set; }
        public DbSet<secteur_point_legal> secteur_point_legal { get; set; }
        public DbSet<signalisation> signalisations { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<db_tournee> db_tournee { get; set; }
        public DbSet<organisation> organisations { get; set; }
        public DbSet<point_legal_20131118> point_legal_20131118 { get; set; }
        public DbSet<secteur_20131118> secteur_20131118 { get; set; }
        public DbSet<secteur_description_20131021> secteur_description_20131021 { get; set; }
        public DbSet<secteur_description_20131118> secteur_description_20131118 { get; set; }
        public DbSet<secteur_description_20140210> secteur_description_20140210 { get; set; }
    }
}
