//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class secteur_historique
    {
        public int secteur_historique_id { get; set; }
        public Nullable<int> operation { get; set; }
        public string auteur { get; set; }
        public Nullable<System.DateTime> date_operation { get; set; }
        public string description { get; set; }
        public Nullable<int> point_legal_id { get; set; }
        public Nullable<int> secteur_id { get; set; }
    }
}
