//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class secteur_20131118
    {
        public int secteur_id { get; set; }
        public Nullable<int> secteur_id_parent { get; set; }
        public string secteur { get; set; }
        public string secteur_ltr { get; set; }
        public Nullable<int> secteur_no1 { get; set; }
        public Nullable<int> secteur_no2 { get; set; }
        public Nullable<int> secteur_no3 { get; set; }
        public Nullable<int> secteur_no4 { get; set; }
        public Nullable<double> longueur_rive { get; set; }
        public Nullable<double> superficie { get; set; }
        public byte[] geometry { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
        public Nullable<double> x_min { get; set; }
        public Nullable<double> y_min { get; set; }
        public Nullable<double> x_max { get; set; }
        public Nullable<double> y_max { get; set; }
        public Nullable<int> secteur_type { get; set; }
        public Nullable<int> etat { get; set; }
        public string description { get; set; }
    }
}
