//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class secteur_coordonnees_epsg_3857
    {
        public int secteur_id { get; set; }
        public Nullable<decimal> C_xmax { get; set; }
        public Nullable<decimal> C_xmin { get; set; }
        public Nullable<decimal> C_ymax { get; set; }
        public Nullable<decimal> C_ymin { get; set; }
    }
}
