//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class secteur_point_archive
    {
        public int secteur_point_archive_id { get; set; }
        public Nullable<int> point_legal_id { get; set; }
        public string secteur1 { get; set; }
        public string secteur2 { get; set; }
        public string secteur3 { get; set; }
        public string secteur4 { get; set; }
        public string secteur5 { get; set; }
    }
}
