//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class secteur_description_20131021
    {
        public int secteur_description_id { get; set; }
        public int secteur_id { get; set; }
        public string secteur_text { get; set; }
        public Nullable<int> langue { get; set; }
        public Nullable<int> parametre { get; set; }
        public Nullable<int> etat { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
    }
}
