//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_tr_code
    {
        public int id_code { get; set; }
        public string descr_fr { get; set; }
        public string descr_en { get; set; }
        public string definition_en { get; set; }
        public string definition_fr { get; set; }
        public string parametre { get; set; }
    }
}
