//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_zone_cotiere
    {
        public int id_zone_cotiere { get; set; }
        public Nullable<int> id_segment { get; set; }
        public Nullable<int> zone_cotiere { get; set; }
        public Nullable<int> pente { get; set; }
        public string acces { get; set; }
        public string limite_acces { get; set; }
        public string relief_forme_construction { get; set; }
        public Nullable<int> classification_substrat { get; set; }
        public string substrat_original { get; set; }
        public string vegetation { get; set; }
    }
}
