//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_segrivB_nad83mdb
    {
        public int MAPINFO_ID { get; set; }
        public string Ident { get; set; }
        public string Municipalité { get; set; }
        public string code_mun { get; set; }
        public string Région { get; set; }
        public string Div_hydrographique { get; set; }
        public Nullable<int> Seg_long { get; set; }
        public string Usage { get; set; }
        public Nullable<short> Zi_larg { get; set; }
        public Nullable<double> superficie { get; set; }
        public string ZSU_relief_acces { get; set; }
        public string ZSU_pente_substrat { get; set; }
        public string ZIS_pente_substrat { get; set; }
        public string ZIS_pente1 { get; set; }
        public string ZIS_substrat1 { get; set; }
        public string ZIM_pente_substrat { get; set; }
        public string ZIM_pente1 { get; set; }
        public string ZIM_substrat1 { get; set; }
        public string ZII_pente_substrat { get; set; }
        public string ZII_pente1 { get; set; }
        public string ZII_substrat1 { get; set; }
        public string Type_côte { get; set; }
        public string Fetch { get; set; }
        public string Processus_dominant { get; set; }
        public string persistance { get; set; }
        public string Limites_acces { get; set; }
        public string Toponymie_locale { get; set; }
        public Nullable<double> Marée_moy { get; set; }
        public Nullable<double> Marée_gra { get; set; }
        public string Carte_topo { get; set; }
        public string Carte_mari { get; set; }
        public string Carte_envc { get; set; }
        public string Info_sources { get; set; }
        public string Commentaires { get; set; }
        public string ZIS_Sub_Class { get; set; }
        public Nullable<int> id_segment { get; set; }
        public Nullable<double> x { get; set; }
    }
}
