//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_processus_dominant
    {
        public int id_processus_dominant { get; set; }
        public Nullable<int> id_segment { get; set; }
        public Nullable<int> processus_dominant { get; set; }
        public Nullable<int> priorite { get; set; }
        public string commentaire_fr { get; set; }
        public string commentaire_en { get; set; }
    }
}
