//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_substrat
    {
        public int id_substrat { get; set; }
        public Nullable<int> id_zone_cotiere { get; set; }
        public Nullable<int> substrat { get; set; }
        public Nullable<int> milieu { get; set; }
        public Nullable<int> priorite { get; set; }
        public Nullable<int> seg_pourcentage { get; set; }
        public string commentaire_fr { get; set; }
        public string commentaire_en { get; set; }
    }
}
