//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class seg_tr_interface_label_new
    {
        public int id_interface_label { get; set; }
        public string table { get; set; }
        public string champ { get; set; }
        public string onglet { get; set; }
        public string groupe { get; set; }
        public string label_fr { get; set; }
        public string label_en { get; set; }
        public bool inclure_ds_form { get; set; }
        public bool utilise_tr_code { get; set; }
        public string param_tr_code { get; set; }
        public bool utilise_tr_source_dvd { get; set; }
        public string description_du_contrôle { get; set; }
    }
}
