//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class segment
    {
        public int id_segment { get; set; }
        public string seg_numero { get; set; }
        public Nullable<int> seg_longueur { get; set; }
        public Nullable<short> zi_largeur { get; set; }
        public Nullable<double> superficie { get; set; }
        public Nullable<int> seg_fetch { get; set; }
        public Nullable<int> seg_source_dvd_deb { get; set; }
        public Nullable<int> seg_index_deb { get; set; }
        public Nullable<System.DateTime> seg_debut { get; set; }
        public Nullable<int> seg_source_dvd_fin { get; set; }
        public Nullable<int> seg_index_fin { get; set; }
        public Nullable<System.DateTime> seg_fin { get; set; }
        public string seg_dvd_commentaire { get; set; }
        public string source_old { get; set; }
        public string municipalite { get; set; }
        public string code_mun { get; set; }
        public Nullable<int> div_hydrographique { get; set; }
        public string toponymie_locale { get; set; }
        public string commentaire_fr { get; set; }
        public string commentaire_en { get; set; }
        public Nullable<int> auteur_segment { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public Nullable<System.DateTime> date_modification { get; set; }
        public Nullable<int> etat { get; set; }
        public Nullable<int> validation { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
    }
}
