//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class segmentation_resultat
    {
        public int Id { get; set; }
        public int id_segment { get; set; }
        public string Numero_segment { get; set; }
        public Nullable<int> zone_cotiere { get; set; }
        public string Substrat { get; set; }
        public string Pente { get; set; }
        public string Type_cote { get; set; }
        public string Forme { get; set; }
        public string commentaire_fr { get; set; }
    }
}
