//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class signalisation
    {
        public int signalisation_id { get; set; }
        public Nullable<System.DateTime> date_installation { get; set; }
        public Nullable<System.DateTime> date_observation { get; set; }
        public Nullable<System.DateTime> date_update { get; set; }
        public string auteur_installation { get; set; }
        public string auteur_update { get; set; }
        public Nullable<int> type_panneau { get; set; }
        public string description { get; set; }
        public Nullable<bool> status_actif { get; set; }
        public string secteur { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
    }
}
