//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCCSM_DFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_secteur
    {
        public int secteur_id { get; set; }
        public string secteur { get; set; }
        public string nomfr { get; set; }
        public string nomen { get; set; }
        public string genen { get; set; }
        public string genfr { get; set; }
        public string legalfr { get; set; }
        public string legalen { get; set; }
        public string secteur_type { get; set; }
        public string etat { get; set; }
        public string regionfr { get; set; }
        public string regionen { get; set; }
        public Nullable<int> Expr1 { get; set; }
    }
}
